CREATE INDEX idx_1 ON SPECIES_ABBREV_structvar__structural_variation__main (structural_variation_id_2072_key);
CREATE INDEX idx_2 ON SPECIES_ABBREV_structvar__structural_variation__main (clinical_significance_2072);
CREATE INDEX idx_3 ON SPECIES_ABBREV_structvar__structural_variation__main (structural_variation_feature_count);
