CREATE INDEX idx_1 ON SPECIES_ABBREV_structvar__structural_variation__main (structural_variation_id_2072_key);
CREATE INDEX idx_2 ON SPECIES_ABBREV_structvar__structural_variation__main (name_2021);
CREATE INDEX idx_3 ON SPECIES_ABBREV_structvar__structural_variation__main (variation_name_2072);
CREATE INDEX idx_4 ON SPECIES_ABBREV_structvar__structural_variation__main (name_20100);
