/* Generated by Together */

/*
    Copyright (C) 2003 EBI, GRL

    This library is free software; you can redistribute it and/or
    modify it under the terms of the GNU Lesser General Public
    License as published by the Free Software Foundation; either
    version 2.1 of the License, or (at your option) any later version.

    This library is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
    Lesser General Public License for more details.

    You should have received a copy of the GNU Lesser General Public
    License along with this library; if not, write to the Free Software
    Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307  USA
 */

package org.ensembl.mart.lib;

/**
 * A field represents a column in one or more tables. It is defined by the 
 * (column) name and an optional constraint limiting the set of tables the name 
 * can refere to.
 * 
 * @author <a href="mailto:craig@ebi.ac.uk">Craig Melsopp</a>
 * @author <a href="mailto:dlondon@ebi.ac.uk">Darin London</a>
 */
public interface Field {

	/**
	 * @return field if available, otherwise null.
	 */
	String getField();

	/**
	 * Sub string that must appear in the name of any table containing 
	 * the column __name__.
	 * @return null or part of a tablename.
	 */
	String getTableConstraint();
	
	/**
	 * @return join field key.
	 */
	String getKey();
}
