/* Generated by Together */

/*
    Copyright (C) 2003 EBI, GRL

    This library is free software; you can redistribute it and/or
    modify it under the terms of the GNU Lesser General Public
    License as published by the Free Software Foundation; either
    version 2.1 of the License, or (at your option) any later version.

    This library is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
    Lesser General Public License for more details.

    You should have received a copy of the GNU Lesser General Public
    License along with this library; if not, write to the Free Software
    Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307  USA
 */
 
package org.ensembl.mart.lib;

/**
 * Signals that an Invalid Query has been specified. 
 */
public class InvalidQueryException extends Exception {
    public InvalidQueryException() {
      super();
    }

    public InvalidQueryException(String message) {
      super( message );
    }

    public InvalidQueryException(String message, Exception exception) {
      super( message, exception );
    }

    public InvalidQueryException(Exception exception) {
      super( exception.getMessage(), exception );
    }
}
