/* Generated by Together */
/*
    Copyright (C) 2003 EBI, GRL

    This library is free software; you can redistribute it and/or
    modify it under the terms of the GNU Lesser General Public
    License as published by the Free Software Foundation; either
    version 2.1 of the License, or (at your option) any later version.

    This library is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
    Lesser General Public License for more details.

    You should have received a copy of the GNU Lesser General Public
    License along with this library; if not, write to the Free Software
    Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307  USA
 */
package org.ensembl.mart.lib;

/**
 * Interface for Filter objects defining standard behavior for use by
 * a Query object.
 * 
 * @author <a href="mailto:craig@ebi.ac.uk">Craig Melsopp</a>
 * @author <a href="mailto:dlondon@ebi.ac.uk">Darin London</a>
 */
public interface Filter extends Field {


    /**
     * Qualifier, null if not needed.  This is used by the UnprcessedFilterHandler implimenting classes
     */
    String getQualifier();
    
    /**
     * Value, null if not needed. This can be added to the prepared statment.
     */
    String getValue();
   
    /**
     * String to be included in where clause.
     * TODO: remove this?
     */
    String getWhereClause();


  /**
   * String representing the "right hand side of the condition". This is any
   * operator and values
   */
  String getRightHandClause();
}
