CREATE INDEX idx_1 ON SPECIES_ABBREV_structvar__structural_variation_feature__main (structural_variation_id_2072_key);
CREATE INDEX idx_2 ON SPECIES_ABBREV_structvar__structural_variation_feature__main (structural_variation_feature_id_20104_key);
CREATE INDEX idx_3 ON SPECIES_ABBREV_structvar__structural_variation_feature__main (structural_variation_feature_count);
