CREATE INDEX idx_1 ON SPECIES_ABBREV_snp__regulatory_feature_variation__dm (variation_feature_id_2026_key);
CREATE INDEX idx_1 ON SPECIES_ABBREV_snp__regulatory_feature_variation__dm (feature_stable_id_20126);
