create table VAR_MART_DB.TEMP0 as select a.validation_status as validation_status_2025,a.minor_allele_freq as minor_allele_freq_2025,a.source_id as source_id_2025,a.ancestral_allele as ancestral_allele_2025,a.name as name_2025,a.somatic as somatic_2025,a.minor_allele as minor_allele_2025,a.class_attrib_id as class_attrib_id_2025,a.variation_id as variation_id_2025_key,a.minor_allele_count as minor_allele_count_2025,a.clinical_significance_attrib_id as clinical_significance_attrib_id_2025 from VAR_DB.variation as a where a.somatic=0;
create index I_0 on VAR_MART_DB.TEMP0(source_id_2025);
create table VAR_MART_DB.TEMP1 as select a.*,b.description as description_2021,b.name as name_2021,b.type as type_2021,b.version as version_2021 from VAR_MART_DB.TEMP0 as a left join VAR_DB.source as b on a.source_id_2025=b.source_id;
drop table VAR_MART_DB.TEMP0;
create index I_1 on VAR_MART_DB.TEMP1(clinical_significance_attrib_id_2025);
create table VAR_MART_DB.TEMP2 as select a.*,b.value as value_2092,b.attrib_type_id as attrib_type_id_2092 from VAR_MART_DB.TEMP1 as a left join VAR_DB.attrib as b on a.clinical_significance_attrib_id_2025=b.attrib_id;
drop table VAR_MART_DB.TEMP1;
create index I_2 on VAR_MART_DB.TEMP2(attrib_type_id_2092);
create table VAR_MART_DB.TEMP3 as select a.*,b.description as description_2094,b.name as name_2094,b.code as code_2094 from VAR_MART_DB.TEMP2 as a left join VAR_DB.attrib_type as b on a.attrib_type_id_2092=b.attrib_type_id;
drop table VAR_MART_DB.TEMP2;
alter table VAR_MART_DB.TEMP3 drop column source_id_2025;
create index I_3 on VAR_MART_DB.TEMP3(name_2025);
create index I_4 on VAR_MART_DB.TEMP3(name_2021);
create index I_5 on VAR_MART_DB.TEMP3(validation_status_2025);
rename table VAR_MART_DB.TEMP3 to VAR_MART_DB.SPECIES_ABBREV_eg_snp__variation__main;
create index I_6 on VAR_MART_DB.SPECIES_ABBREV_eg_snp__variation__main(variation_id_2025_key);
create table VAR_MART_DB.TEMP4 as select a.variation_id_2025_key from VAR_MART_DB.SPECIES_ABBREV_eg_snp__variation__main as a;
create index I_7 on VAR_MART_DB.TEMP4(variation_id_2025_key);
create table VAR_MART_DB.TEMP5 as select a.*,b.risk_allele_freq_in_controls as risk_allele_freq_in_controls_2035,b.associated_variant_risk_allele as associated_variant_risk_allele_2035,b.study_id as study_id_2035,b.associated_gene as associated_gene_2035,b.p_value as p_value_2035,b.variation_names as variation_names_2035,b.variation_annotation_id as variation_annotation_id_2035,b.phenotype_id as phenotype_id_2035 from VAR_MART_DB.TEMP4 as a inner join VAR_DB.variation_annotation as b on a.variation_id_2025_key=b.variation_id;
drop table VAR_MART_DB.TEMP4;
create index I_8 on VAR_MART_DB.TEMP5(phenotype_id_2035);
create table VAR_MART_DB.TEMP6 as select a.*,b.description as description_2033,b.name as name_2033 from VAR_MART_DB.TEMP5 as a inner join VAR_DB.phenotype as b on a.phenotype_id_2035=b.phenotype_id;
drop table VAR_MART_DB.TEMP5;
create index I_9 on VAR_MART_DB.TEMP6(study_id_2035);
create table VAR_MART_DB.TEMP7 as select a.*,b.external_reference as external_reference_20100,b.source_id as source_id_20100,b.description as description_20100,b.name as name_20100,b.study_type as study_type_20100,b.url as url_20100 from VAR_MART_DB.TEMP6 as a inner join VAR_DB.study as b on a.study_id_2035=b.study_id;
drop table VAR_MART_DB.TEMP6;
create index I_10 on VAR_MART_DB.TEMP7(source_id_20100);
create table VAR_MART_DB.TEMP8 as select a.*,b.description as description_2021,b.name as name_2021,b.type as type_2021 from VAR_MART_DB.TEMP7 as a inner join VAR_DB.source as b on a.source_id_20100=b.source_id;
drop table VAR_MART_DB.TEMP7;
create index I_11 on VAR_MART_DB.TEMP8(variation_id_2025_key);
create table VAR_MART_DB.TEMP9 as select a.variation_id_2025_key,b.source_id_20100,b.description_2021,b.variation_annotation_id_2035,b.url_20100,b.external_reference_20100,b.type_2021,b.phenotype_id_2035,b.description_20100,b.risk_allele_freq_in_controls_2035,b.name_2033,b.study_type_20100,b.associated_variant_risk_allele_2035,b.description_2033,b.study_id_2035,b.name_2021,b.name_20100,b.associated_gene_2035,b.p_value_2035,b.variation_names_2035 from VAR_MART_DB.SPECIES_ABBREV_eg_snp__variation__main as a left join VAR_MART_DB.TEMP8 as b on a.variation_id_2025_key=b.variation_id_2025_key;
drop table VAR_MART_DB.TEMP8;
alter table VAR_MART_DB.TEMP9 drop column variation_annotation_id_2035;
alter table VAR_MART_DB.TEMP9 drop column phenotype_id_2035;
rename table VAR_MART_DB.TEMP9 to VAR_MART_DB.SPECIES_ABBREV_eg_snp__variation_annotation__dm;
create index I_12 on VAR_MART_DB.SPECIES_ABBREV_eg_snp__variation_annotation__dm(variation_id_2025_key);
alter table VAR_MART_DB.SPECIES_ABBREV_eg_snp__variation__main add column (variation_annotation_bool integer default 0);
update VAR_MART_DB.SPECIES_ABBREV_eg_snp__variation__main a set variation_annotation_bool=(select case count(1) when 0 then null else 1 end from VAR_MART_DB.SPECIES_ABBREV_eg_snp__variation_annotation__dm b where a.variation_id_2025_key=b.variation_id_2025_key and not (b.source_id_20100 is null and b.description_2021 is null and b.url_20100 is null and b.external_reference_20100 is null and b.type_2021 is null and b.description_20100 is null and b.risk_allele_freq_in_controls_2035 is null and b.name_2033 is null and b.study_type_20100 is null and b.associated_variant_risk_allele_2035 is null and b.description_2033 is null and b.study_id_2035 is null and b.name_2021 is null and b.name_20100 is null and b.associated_gene_2035 is null and b.p_value_2035 is null and b.variation_names_2035 is null));
create index I_13 on VAR_MART_DB.SPECIES_ABBREV_eg_snp__variation__main(variation_annotation_bool);
create table VAR_MART_DB.TEMP10 as select a.source_id as source_id_2021,a.description as description_2021,a.name as name_2021,a.type as type_2021,a.version as version_2021 from VAR_DB.source as a where a.source_id='1';
create index I_14 on VAR_MART_DB.TEMP10(source_id_2021);
create table VAR_MART_DB.TEMP11 as select a.*,b.subsnp_id as subsnp_id_2030,b.name as name_2030,b.moltype as moltype_2030,b.variation_id as variation_id_2025_key,b.variation_synonym_id as variation_synonym_id_2030 from VAR_MART_DB.TEMP10 as a inner join VAR_DB.variation_synonym as b on a.source_id_2021=b.source_id;
drop table VAR_MART_DB.TEMP10;
create index I_15 on VAR_MART_DB.TEMP11(variation_id_2025_key);
create table VAR_MART_DB.TEMP13 as select a.* from VAR_MART_DB.TEMP11 as a inner join VAR_MART_DB.SPECIES_ABBREV_eg_snp__variation__main as b on a.variation_id_2025_key=b.variation_id_2025_key;
drop table VAR_MART_DB.TEMP11;
create index I_16 on VAR_MART_DB.TEMP13(variation_id_2025_key);
create table VAR_MART_DB.TEMP14 as select a.variation_id_2025_key,b.source_id_2021,b.description_2021,b.version_2021,b.type_2021,b.moltype_2030,b.variation_synonym_id_2030,b.name_2030,b.name_2021,b.subsnp_id_2030 from VAR_MART_DB.SPECIES_ABBREV_eg_snp__variation__main as a left join VAR_MART_DB.TEMP13 as b on a.variation_id_2025_key=b.variation_id_2025_key;
drop table VAR_MART_DB.TEMP13;
alter table VAR_MART_DB.TEMP14 drop column subsnp_id_2030;
create index I_17 on VAR_MART_DB.TEMP14(name_2030);
create index I_18 on VAR_MART_DB.TEMP14(name_2021);
rename table VAR_MART_DB.TEMP14 to VAR_MART_DB.SPECIES_ABBREV_eg_snp__variation_synonym_SGRP__dm;
create index I_19 on VAR_MART_DB.SPECIES_ABBREV_eg_snp__variation_synonym_SGRP__dm(variation_id_2025_key);
alter table VAR_MART_DB.SPECIES_ABBREV_eg_snp__variation__main add column (variation_synonym_SGRP_bool integer default 0);
update VAR_MART_DB.SPECIES_ABBREV_eg_snp__variation__main a set variation_synonym_SGRP_bool=(select case count(1) when 0 then null else 1 end from VAR_MART_DB.SPECIES_ABBREV_eg_snp__variation_synonym_SGRP__dm b where a.variation_id_2025_key=b.variation_id_2025_key and not (b.source_id_2021 is null and b.description_2021 is null and b.version_2021 is null and b.type_2021 is null and b.moltype_2030 is null and b.variation_synonym_id_2030 is null and b.name_2030 is null and b.name_2021 is null));
create index I_20 on VAR_MART_DB.SPECIES_ABBREV_eg_snp__variation__main(variation_synonym_SGRP_bool);
create table VAR_MART_DB.TEMP15 as select a.variation_id_2025_key from VAR_MART_DB.SPECIES_ABBREV_eg_snp__variation__main as a;
create index I_21 on VAR_MART_DB.TEMP15(variation_id_2025_key);
create table VAR_MART_DB.TEMP16 as select a.*,b.subsnp_id as subsnp_id_2023,b.allele_1 as allele_1_2023,b.allele_2 as allele_2_2023,b.sample_id as sample_id_2023 from VAR_MART_DB.TEMP15 as a left join VAR_DB.tmp_individual_genotype_single_bp as b on a.variation_id_2025_key=b.variation_id;
drop table VAR_MART_DB.TEMP15;
create index I_22 on VAR_MART_DB.TEMP16(sample_id_2023);
create table VAR_MART_DB.TEMP18 as select a.*,b.description as description_2019,b.name as name_2019,b.display as display_2019,b.size as size_2019 from VAR_MART_DB.TEMP16 as a inner join VAR_DB.sample as b on a.sample_id_2023=b.sample_id and (b.display in ("REFERENCE","DEFAULT","UNDISPLAYABLE","DISPLAYABLE","MARTDISPLAYABLE"));
drop table VAR_MART_DB.TEMP16;
create table VAR_MART_DB.TEMP20 as select name_2019,allele_2_2023,size_2019,sample_id_2023,display_2019,description_2019,variation_id_2025_key,subsnp_id_2023,allele_1_2023,concat(allele_1_2023, '|', allele_2_2023) as allele from VAR_MART_DB.TEMP18;
drop table VAR_MART_DB.TEMP18;
create index I_23 on VAR_MART_DB.TEMP20(variation_id_2025_key);
create table VAR_MART_DB.TEMP21 as select a.variation_id_2025_key,b.size_2019,b.subsnp_id_2023,b.name_2019,b.allele_2_2023,b.allele,b.allele_1_2023,b.display_2019,b.description_2019,b.sample_id_2023 from VAR_MART_DB.SPECIES_ABBREV_eg_snp__variation__main as a left join VAR_MART_DB.TEMP20 as b on a.variation_id_2025_key=b.variation_id_2025_key;
drop table VAR_MART_DB.TEMP20;
create table VAR_MART_DB.TEMP22 as select distinct name_2019,allele,size_2019,sample_id_2023,display_2019,description_2019,variation_id_2025_key from VAR_MART_DB.TEMP21;
drop table VAR_MART_DB.TEMP21;
create index I_24 on VAR_MART_DB.TEMP22(name_2019);
rename table VAR_MART_DB.TEMP22 to VAR_MART_DB.SPECIES_ABBREV_eg_snp__poly__dm;
create index I_25 on VAR_MART_DB.SPECIES_ABBREV_eg_snp__poly__dm(variation_id_2025_key);
create table VAR_MART_DB.TEMP23 as select a.variation_id_2025_key from VAR_MART_DB.SPECIES_ABBREV_eg_snp__variation__main as a;
create index I_26 on VAR_MART_DB.TEMP23(variation_id_2025_key);
create table VAR_MART_DB.TEMP24 as select a.*,b.population_genotype_id as population_genotype_id_20107,b.allele_1 as allele_1_20107,b.allele_2 as allele_2_20107,b.sample_id as sample_id_20107,b.frequency as frequency_2016 from VAR_MART_DB.TEMP23 as a inner join VAR_DB.MTMP_population_genotype as b on a.variation_id_2025_key=b.variation_id;
drop table VAR_MART_DB.TEMP23;
create index I_27 on VAR_MART_DB.TEMP24(sample_id_20107);
create table VAR_MART_DB.TEMP25 as select a.*,b.name as name_2019 from VAR_MART_DB.TEMP24 as a inner join VAR_DB.sample as b on a.sample_id_20107=b.sample_id;
drop table VAR_MART_DB.TEMP24;
create table VAR_MART_DB.TEMP27 as select name_2019,frequency_2016,allele_2_20107,sample_id_20107,variation_id_2025_key,allele_1_20107,population_genotype_id_20107,concat(allele_1_20107, '|', allele_2_20107) as allele from VAR_MART_DB.TEMP25;
drop table VAR_MART_DB.TEMP25;
create index I_28 on VAR_MART_DB.TEMP27(variation_id_2025_key);
create table VAR_MART_DB.TEMP28 as select a.variation_id_2025_key,b.allele_1_20107,b.name_2019,b.allele,b.sample_id_20107,b.population_genotype_id_20107,b.allele_2_20107,b.frequency_2016 from VAR_MART_DB.SPECIES_ABBREV_eg_snp__variation__main as a left join VAR_MART_DB.TEMP27 as b on a.variation_id_2025_key=b.variation_id_2025_key;
drop table VAR_MART_DB.TEMP27;
alter table VAR_MART_DB.TEMP28 drop column allele_1_20107;
alter table VAR_MART_DB.TEMP28 drop column sample_id_20107;
alter table VAR_MART_DB.TEMP28 drop column population_genotype_id_20107;
alter table VAR_MART_DB.TEMP28 drop column allele_2_20107;
rename table VAR_MART_DB.TEMP28 to VAR_MART_DB.SPECIES_ABBREV_eg_snp__population_genotype__dm;
create index I_29 on VAR_MART_DB.SPECIES_ABBREV_eg_snp__population_genotype__dm(variation_id_2025_key);
alter table VAR_MART_DB.SPECIES_ABBREV_eg_snp__variation__main add column (population_genotype_bool integer default 0);
update VAR_MART_DB.SPECIES_ABBREV_eg_snp__variation__main a set population_genotype_bool=(select case count(1) when 0 then null else 1 end from VAR_MART_DB.SPECIES_ABBREV_eg_snp__population_genotype__dm b where a.variation_id_2025_key=b.variation_id_2025_key and not (b.name_2019 is null and b.frequency_2016 is null));
create index I_30 on VAR_MART_DB.SPECIES_ABBREV_eg_snp__variation__main(population_genotype_bool);
create table VAR_MART_DB.TEMP29 as select a.variation_id_2025_key from VAR_MART_DB.SPECIES_ABBREV_eg_snp__variation__main as a;
create index I_31 on VAR_MART_DB.TEMP29(variation_id_2025_key);
create table VAR_MART_DB.TEMP30 as select a.*,b.variation_set_id as variation_set_id_2078 from VAR_MART_DB.TEMP29 as a inner join VAR_DB.variation_set_variation as b on a.variation_id_2025_key=b.variation_id;
drop table VAR_MART_DB.TEMP29;
create index I_32 on VAR_MART_DB.TEMP30(variation_set_id_2078);
create table VAR_MART_DB.TEMP31 as select a.*,b.description as description_2077,b.name as name_2077,b.short_name_attrib_id as short_name_attrib_id_2077 from VAR_MART_DB.TEMP30 as a inner join VAR_DB.variation_set as b on a.variation_set_id_2078=b.variation_set_id;
drop table VAR_MART_DB.TEMP30;
create index I_33 on VAR_MART_DB.TEMP31(variation_id_2025_key);
create table VAR_MART_DB.TEMP32 as select a.variation_id_2025_key,b.short_name_attrib_id_2077,b.description_2077,b.name_2077,b.variation_set_id_2078 from VAR_MART_DB.SPECIES_ABBREV_eg_snp__variation__main as a left join VAR_MART_DB.TEMP31 as b on a.variation_id_2025_key=b.variation_id_2025_key;
drop table VAR_MART_DB.TEMP31;
create index I_34 on VAR_MART_DB.TEMP32(name_2077);
rename table VAR_MART_DB.TEMP32 to VAR_MART_DB.SPECIES_ABBREV_eg_snp__variation_set_variation__dm;
create index I_35 on VAR_MART_DB.SPECIES_ABBREV_eg_snp__variation_set_variation__dm(variation_id_2025_key);
alter table VAR_MART_DB.SPECIES_ABBREV_eg_snp__variation__main add column (variation_set_variation_bool integer default 0);
update VAR_MART_DB.SPECIES_ABBREV_eg_snp__variation__main a set variation_set_variation_bool=(select case count(1) when 0 then null else 1 end from VAR_MART_DB.SPECIES_ABBREV_eg_snp__variation_set_variation__dm b where a.variation_id_2025_key=b.variation_id_2025_key and not (b.short_name_attrib_id_2077 is null and b.description_2077 is null and b.name_2077 is null and b.variation_set_id_2078 is null));
create index I_36 on VAR_MART_DB.SPECIES_ABBREV_eg_snp__variation__main(variation_set_variation_bool);
create table VAR_MART_DB.TEMP33 as select a.variation_id_2025_key from VAR_MART_DB.SPECIES_ABBREV_eg_snp__variation__main as a;
create index I_37 on VAR_MART_DB.TEMP33(variation_id_2025_key);
create table VAR_MART_DB.TEMP34 as select a.*,b.subsnp_id as subsnp_id_2010,b.allele_1 as allele_1_2010,b.allele_2 as allele_2_2010,b.sample_id as sample_id_2010 from VAR_MART_DB.TEMP33 as a left join VAR_DB.individual_genotype_multiple_bp as b on a.variation_id_2025_key=b.variation_id;
drop table VAR_MART_DB.TEMP33;
create index I_38 on VAR_MART_DB.TEMP34(sample_id_2010);
create table VAR_MART_DB.TEMP36 as select a.*,b.description as description_2019,b.name as name_2019,b.display as display_2019,b.size as size_2019 from VAR_MART_DB.TEMP34 as a inner join VAR_DB.sample as b on a.sample_id_2010=b.sample_id and (b.display in ("REFERENCE","DEFAULT","DISPLAYABLE","MARTDISPLAYABLE"));
drop table VAR_MART_DB.TEMP34;
create table VAR_MART_DB.TEMP38 as select name_2019,allele_2_2010,size_2019,sample_id_2010,display_2019,description_2019,variation_id_2025_key,subsnp_id_2010,allele_1_2010,concat(allele_1_2010, '|', allele_2_2010) as allele from VAR_MART_DB.TEMP36;
drop table VAR_MART_DB.TEMP36;
create index I_39 on VAR_MART_DB.TEMP38(variation_id_2025_key);
create table VAR_MART_DB.TEMP39 as select a.variation_id_2025_key,b.size_2019,b.name_2019,b.allele_2_2010,b.allele_1_2010,b.allele,b.sample_id_2010,b.display_2019,b.subsnp_id_2010,b.description_2019 from VAR_MART_DB.SPECIES_ABBREV_eg_snp__variation__main as a left join VAR_MART_DB.TEMP38 as b on a.variation_id_2025_key=b.variation_id_2025_key;
drop table VAR_MART_DB.TEMP38;
create table VAR_MART_DB.TEMP40 as select distinct name_2019,allele,size_2019,sample_id_2010,display_2019,description_2019,variation_id_2025_key from VAR_MART_DB.TEMP39;
drop table VAR_MART_DB.TEMP39;
create index I_40 on VAR_MART_DB.TEMP40(name_2019);
rename table VAR_MART_DB.TEMP40 to VAR_MART_DB.SPECIES_ABBREV_eg_snp__mpoly__dm;
create index I_41 on VAR_MART_DB.SPECIES_ABBREV_eg_snp__mpoly__dm(variation_id_2025_key);
create table VAR_MART_DB.TEMP41 as select a.description_2021,a.attrib_type_id_2092,a.clinical_significance_attrib_id_2025,a.value_2092,a.name_2094,a.version_2021,a.class_attrib_id_2025,a.name_2021,a.variation_set_variation_bool,a.name_2025,a.minor_allele_freq_2025,a.type_2021,a.minor_allele_2025,a.minor_allele_count_2025,a.description_2094,a.ancestral_allele_2025,a.validation_status_2025,a.variation_annotation_bool,a.variation_id_2025_key,a.code_2094,a.population_genotype_bool,a.variation_synonym_SGRP_bool,a.somatic_2025 from VAR_MART_DB.SPECIES_ABBREV_eg_snp__variation__main as a;
create index I_42 on VAR_MART_DB.TEMP41(variation_id_2025_key);
create table VAR_MART_DB.TEMP42 as select a.*,b.alignment_quality as alignment_quality_2026,b.validation_status as validation_status_2026,b.flags as flags_2026,b.seq_region_id as seq_region_id_2026,b.variation_name as variation_name_2026,b.source_id as source_id_2026,b.somatic as somatic_2026,b.map_weight as map_weight_2026,b.variation_set_id as variation_set_id_2026,b.allele_string as allele_string_2026,b.seq_region_end as seq_region_end_2026,b.variation_feature_id as variation_feature_id_2026_key,b.seq_region_start as seq_region_start_2026,b.class_attrib_id as class_attrib_id_2026,b.seq_region_strand as seq_region_strand_2026 from VAR_MART_DB.TEMP41 as a left join VAR_DB.variation_feature as b on a.variation_id_2025_key=b.variation_id;
drop table VAR_MART_DB.TEMP41;
create index I_43 on VAR_MART_DB.TEMP42(source_id_2026);
create table VAR_MART_DB.TEMP43 as select a.*,b.description as description_2021_r1,b.name as name_2021_r1,b.type as type_2021_r1,b.version as version_2021_r1 from VAR_MART_DB.TEMP42 as a left join VAR_DB.source as b on a.source_id_2026=b.source_id;
drop table VAR_MART_DB.TEMP42;
create index I_44 on VAR_MART_DB.TEMP43(seq_region_id_2026);
create table VAR_MART_DB.TEMP44 as select a.*,b.name as name_1059,b.coord_system_id as coord_system_id_1059 from VAR_MART_DB.TEMP43 as a left join CORE_DB.seq_region as b on a.seq_region_id_2026=b.seq_region_id;
drop table VAR_MART_DB.TEMP43;
create index I_45 on VAR_MART_DB.TEMP44(seq_region_id_2026);
create table VAR_MART_DB.TEMP46 as select a.*,b.name as name_2034,b.coord_system_id as coord_system_id_2034 from VAR_MART_DB.TEMP44 as a left join VAR_DB.seq_region as b on a.seq_region_id_2026=b.seq_region_id;
drop table VAR_MART_DB.TEMP44;
create index I_46 on VAR_MART_DB.TEMP46(variation_set_id_2026);
create table VAR_MART_DB.TEMP47 as select a.*,b.description as description_2077,b.name as name_2077,b.short_name_attrib_id as short_name_attrib_id_2077 from VAR_MART_DB.TEMP46 as a left join VAR_DB.variation_set as b on a.variation_set_id_2026=b.variation_set_id;
drop table VAR_MART_DB.TEMP46;
alter table VAR_MART_DB.TEMP47 drop column coord_system_id_1059;
alter table VAR_MART_DB.TEMP47 drop column source_id_2026;
create index I_47 on VAR_MART_DB.TEMP47(seq_region_start_2026);
create index I_48 on VAR_MART_DB.TEMP47(validation_status_2026);
create index I_49 on VAR_MART_DB.TEMP47(name_1059);
create index I_50 on VAR_MART_DB.TEMP47(name_2021_r1);
create index I_51 on VAR_MART_DB.TEMP47(name_2025);
rename table VAR_MART_DB.TEMP47 to VAR_MART_DB.SPECIES_ABBREV_eg_snp__variation_feature__main;
create index I_52 on VAR_MART_DB.SPECIES_ABBREV_eg_snp__variation_feature__main(variation_id_2025_key);
create index I_53 on VAR_MART_DB.SPECIES_ABBREV_eg_snp__variation_feature__main(variation_feature_id_2026_key);
alter table VAR_MART_DB.SPECIES_ABBREV_eg_snp__variation__main add column (variation_feature_count integer default 0);
update VAR_MART_DB.SPECIES_ABBREV_eg_snp__variation__main a set variation_feature_count=(select count(1) from VAR_MART_DB.SPECIES_ABBREV_eg_snp__variation_feature__main b where a.variation_id_2025_key=b.variation_id_2025_key and not (b.description_2021 is null and b.version_2021_r1 is null and b.class_attrib_id_2025 is null and b.coord_system_id_2034 is null and b.seq_region_start_2026 is null and b.validation_status_2026 is null and b.variation_feature_id_2026_key is null and b.variation_set_id_2026 is null and b.value_2092 is null and b.name_2034 is null and b.type_2021_r1 is null and b.class_attrib_id_2026 is null and b.allele_string_2026 is null and b.minor_allele_2025 is null and b.name_1059 is null and b.description_2094 is null and b.name_2021_r1 is null and b.ancestral_allele_2025 is null and b.short_name_attrib_id_2077 is null and b.attrib_type_id_2092 is null and b.clinical_significance_attrib_id_2025 is null and b.description_2021_r1 is null and b.name_2094 is null and b.minor_allele_freq_2025 is null and b.description_2077 is null and b.flags_2026 is null and b.validation_status_2025 is null and b.somatic_2026 is null and b.alignment_quality_2026 is null and b.version_2021 is null and b.name_2021 is null and b.name_2025 is null and b.seq_region_id_2026 is null and b.seq_region_end_2026 is null and b.seq_region_strand_2026 is null and b.type_2021 is null and b.minor_allele_count_2025 is null and b.variation_name_2026 is null and b.map_weight_2026 is null and b.name_2077 is null and b.code_2094 is null and b.somatic_2025 is null));
create index I_54 on VAR_MART_DB.SPECIES_ABBREV_eg_snp__variation__main(variation_feature_count);
alter table VAR_MART_DB.SPECIES_ABBREV_eg_snp__variation_feature__main add column (variation_feature_count integer default 0);
update VAR_MART_DB.SPECIES_ABBREV_eg_snp__variation_feature__main a set variation_feature_count=(select max(variation_feature_count) from VAR_MART_DB.SPECIES_ABBREV_eg_snp__variation__main b where a.variation_id_2025_key=b.variation_id_2025_key);
create index I_55 on VAR_MART_DB.SPECIES_ABBREV_eg_snp__variation_feature__main(variation_feature_count);
create table VAR_MART_DB.TEMP48 as select a.variation_feature_id_2026_key from VAR_MART_DB.SPECIES_ABBREV_eg_snp__variation_feature__main as a;
create index I_56 on VAR_MART_DB.TEMP48(variation_feature_id_2026_key);
create table VAR_MART_DB.TEMP49 as select a.*,b.tagged_variation_feature_id as tagged_variation_feature_id_2022,b.sample_id as sample_id_2022 from VAR_MART_DB.TEMP48 as a inner join VAR_DB.tagged_variation_feature as b on a.variation_feature_id_2026_key=b.variation_feature_id;
drop table VAR_MART_DB.TEMP48;
create index I_57 on VAR_MART_DB.TEMP49(sample_id_2022);
create table VAR_MART_DB.TEMP50 as select a.*,b.description as description_2019,b.name as name_2019,b.display as display_2019,b.size as size_2019 from VAR_MART_DB.TEMP49 as a inner join VAR_DB.sample as b on a.sample_id_2022=b.sample_id;
drop table VAR_MART_DB.TEMP49;
create index I_58 on VAR_MART_DB.TEMP50(variation_feature_id_2026_key);
create table VAR_MART_DB.TEMP52 as select a.variation_feature_id_2026_key,b.size_2019,b.display_2019,b.name_2019,b.description_2019,b.sample_id_2022,b.tagged_variation_feature_id_2022 from VAR_MART_DB.SPECIES_ABBREV_eg_snp__variation_feature__main as a left join VAR_MART_DB.TEMP50 as b on a.variation_feature_id_2026_key=b.variation_feature_id_2026_key;
drop table VAR_MART_DB.TEMP50;
rename table VAR_MART_DB.TEMP52 to VAR_MART_DB.SPECIES_ABBREV_eg_snp__tagged_variation_feature__dm;
create index I_59 on VAR_MART_DB.SPECIES_ABBREV_eg_snp__tagged_variation_feature__dm(variation_feature_id_2026_key);
alter table VAR_MART_DB.SPECIES_ABBREV_eg_snp__variation_feature__main add column (tagged_variation_feature_bool integer default 0);
update VAR_MART_DB.SPECIES_ABBREV_eg_snp__variation_feature__main a set tagged_variation_feature_bool=(select case count(1) when 0 then null else 1 end from VAR_MART_DB.SPECIES_ABBREV_eg_snp__tagged_variation_feature__dm b where a.variation_feature_id_2026_key=b.variation_feature_id_2026_key and not (b.size_2019 is null and b.display_2019 is null and b.name_2019 is null and b.description_2019 is null and b.sample_id_2022 is null and b.tagged_variation_feature_id_2022 is null));
create index I_60 on VAR_MART_DB.SPECIES_ABBREV_eg_snp__variation_feature__main(tagged_variation_feature_bool);
create table VAR_MART_DB.TEMP53 as select a.seq_region_id as seq_region_id_1020,a.stable_id as stable_id_1023,a.source as source_1020,a.seq_region_start as seq_region_start_1020,a.status as status_1020,a.analysis_id as analysis_id_1020,a.biotype as biotype_1020,a.canonical_annotation as canonical_annotation_1020,a.display_xref_id as display_xref_id_1020,a.gene_id as gene_id_1020,a.seq_region_strand as seq_region_strand_1020,a.seq_region_end as seq_region_end_1020 from CORE_DB.gene as a;
create index I_61 on VAR_MART_DB.TEMP53(gene_id_1020);
create table VAR_MART_DB.TEMP56 as select a.*,b.transcript_id as transcript_id_1064,b.seq_region_id as seq_region_id_1064,b.stable_id as stable_id_1066,b.seq_region_start as seq_region_start_1064,b.status as status_1064,b.analysis_id as analysis_id_1064,b.biotype as biotype_1064,b.display_xref_id as display_xref_id_1064,b.seq_region_strand as seq_region_strand_1064,b.seq_region_end as seq_region_end_1064 from VAR_MART_DB.TEMP53 as a inner join CORE_DB.transcript as b on a.gene_id_1020=b.gene_id;
drop table VAR_MART_DB.TEMP53;
create index I_62 on VAR_MART_DB.TEMP56(stable_id_1066);
create table VAR_MART_DB.TEMP59 as select a.*,b.polyphen_prediction as polyphen_prediction_2090,b.cds_end as cds_end_2090,b.pep_allele_string as pep_allele_string_2090,b.cdna_end as cdna_end_2090,b.cds_start as cds_start_2090,b.sift_prediction as sift_prediction_2090,b.cdna_start as cdna_start_2090,b.allele_string as allele_string_2090,b.sift_score as sift_score_2090,b.variation_feature_id as variation_feature_id_2026_key,b.distance_to_transcript as distance_to_transcript_2090,b.consequence_types as consequence_types_2090,b.polyphen_score as polyphen_score_2090,b.translation_end as translation_end_2090,b.translation_start as translation_start_2090 from VAR_MART_DB.TEMP56 as a inner join VAR_DB.MTMP_transcript_variation as b on a.stable_id_1066=b.feature_stable_id;
drop table VAR_MART_DB.TEMP56;
create index I_63 on VAR_MART_DB.TEMP59(variation_feature_id_2026_key);
create table VAR_MART_DB.TEMP60 as select a.* from VAR_MART_DB.TEMP59 as a inner join VAR_MART_DB.SPECIES_ABBREV_eg_snp__variation_feature__main as b on a.variation_feature_id_2026_key=b.variation_feature_id_2026_key;
drop table VAR_MART_DB.TEMP59;
create index I_64 on VAR_MART_DB.TEMP60(variation_feature_id_2026_key);
create table VAR_MART_DB.TEMP61 as select a.variation_feature_id_2026_key,b.allele_string_2090,b.stable_id_1023,b.cds_start_2090,b.cdna_end_2090,b.seq_region_strand_1020,b.polyphen_prediction_2090,b.translation_end_2090,b.status_1020,b.sift_score_2090,b.seq_region_id_1020,b.consequence_types_2090,b.status_1064,b.seq_region_strand_1064,b.display_xref_id_1020,b.seq_region_start_1020,b.seq_region_id_1064,b.display_xref_id_1064,b.canonical_annotation_1020,b.pep_allele_string_2090,b.analysis_id_1020,b.seq_region_end_1064,b.stable_id_1066,b.sift_prediction_2090,b.transcript_id_1064,b.distance_to_transcript_2090,b.seq_region_start_1064,b.gene_id_1020,b.biotype_1020,b.cdna_start_2090,b.translation_start_2090,b.cds_end_2090,b.source_1020,b.analysis_id_1064,b.polyphen_score_2090,b.seq_region_end_1020,b.biotype_1064 from VAR_MART_DB.SPECIES_ABBREV_eg_snp__variation_feature__main as a left join VAR_MART_DB.TEMP60 as b on a.variation_feature_id_2026_key=b.variation_feature_id_2026_key;
drop table VAR_MART_DB.TEMP60;
alter table VAR_MART_DB.TEMP61 drop column seq_region_id_1020;
alter table VAR_MART_DB.TEMP61 drop column seq_region_id_1064;
alter table VAR_MART_DB.TEMP61 drop column analysis_id_1020;
alter table VAR_MART_DB.TEMP61 drop column analysis_id_1064;
create index I_65 on VAR_MART_DB.TEMP61(stable_id_1023);
create index I_66 on VAR_MART_DB.TEMP61(polyphen_prediction_2090);
create index I_67 on VAR_MART_DB.TEMP61(consequence_types_2090);
create index I_68 on VAR_MART_DB.TEMP61(stable_id_1066);
create index I_69 on VAR_MART_DB.TEMP61(sift_prediction_2090);
create index I_70 on VAR_MART_DB.TEMP61(cdna_start_2090);
create index I_71 on VAR_MART_DB.TEMP61(translation_start_2090);
rename table VAR_MART_DB.TEMP61 to VAR_MART_DB.SPECIES_ABBREV_eg_snp__mart_transcript_variation__dm;
create index I_72 on VAR_MART_DB.SPECIES_ABBREV_eg_snp__mart_transcript_variation__dm(variation_feature_id_2026_key);

