create table VAR_MART_DB.TEMP136 as select a.validation_status as validation_status_2072,a.variation_name as variation_name_2072,a.structural_variation_id as structural_variation_id_2072_key,a.source_id as source_id_2072,a.study_id as study_id_2072,a.class_attrib_id as class_attrib_id_2072 from VAR_DB.structural_variation as a where a.is_evidence=0 and a.somatic=0;
create index I_158 on VAR_MART_DB.TEMP136(source_id_2072);
create table VAR_MART_DB.TEMP137 as select a.*,b.description as description_2021,b.name as name_2021 from VAR_MART_DB.TEMP136 as a left join VAR_DB.source as b on a.source_id_2072=b.source_id;
drop table VAR_MART_DB.TEMP136;
create index I_159 on VAR_MART_DB.TEMP137(class_attrib_id_2072);
create table VAR_MART_DB.TEMP139 as select a.*,b.value as value_2092,b.attrib_type_id as attrib_type_id_2092 from VAR_MART_DB.TEMP137 as a left join VAR_DB.attrib as b on a.class_attrib_id_2072=b.attrib_id;
drop table VAR_MART_DB.TEMP137;
create index I_160 on VAR_MART_DB.TEMP139(attrib_type_id_2092);
create table VAR_MART_DB.TEMP140 as select a.* from VAR_MART_DB.TEMP139 as a left join VAR_DB.attrib_type as b on a.attrib_type_id_2092=b.attrib_type_id;
drop table VAR_MART_DB.TEMP139;
create index I_161 on VAR_MART_DB.TEMP140(study_id_2072);
create table VAR_MART_DB.TEMP141 as select a.*,b.external_reference as external_reference_20100,b.source_id as source_id_20100,b.description as description_20100,b.name as name_20100 from VAR_MART_DB.TEMP140 as a left join VAR_DB.study as b on a.study_id_2072=b.study_id;
drop table VAR_MART_DB.TEMP140;
create index I_162 on VAR_MART_DB.TEMP141(source_id_20100);
create table VAR_MART_DB.TEMP142 as select a.* from VAR_MART_DB.TEMP141 as a left join VAR_DB.source as b on a.source_id_20100=b.source_id;
drop table VAR_MART_DB.TEMP141;
rename table VAR_MART_DB.TEMP142 to VAR_MART_DB.SPECIES_ABBREV_structvar__structural_variation__main;
create index I_163 on VAR_MART_DB.SPECIES_ABBREV_structvar__structural_variation__main(structural_variation_id_2072_key);
create table VAR_MART_DB.TEMP144 as select a.structural_variation_id_2072_key from VAR_MART_DB.SPECIES_ABBREV_structvar__structural_variation__main as a;
create index I_164 on VAR_MART_DB.TEMP144(structural_variation_id_2072_key);
create table VAR_MART_DB.TEMP145 as select a.*,b.structural_variation_sample_id as structural_variation_sample_id_20138,b.strain_id as strain_id_20138,b.individual_id as individual_id_20138 from VAR_MART_DB.TEMP144 as a inner join VAR_DB.structural_variation_sample as b on a.structural_variation_id_2072_key=b.structural_variation_id;
drop table VAR_MART_DB.TEMP144;
create index I_165 on VAR_MART_DB.TEMP145(strain_id_20138);
create table VAR_MART_DB.TEMP146 as select a.*,b.individual_type_id as individual_type_id_2019,b.description as description_2019,b.name as name_2019 from VAR_MART_DB.TEMP145 as a inner join VAR_DB.individual as b on a.strain_id_20138=b.individual_id;
drop table VAR_MART_DB.TEMP145;
create index I_166 on VAR_MART_DB.TEMP146(individual_type_id_2019);
create table VAR_MART_DB.TEMP147 as select a.* from VAR_MART_DB.TEMP146 as a inner join VAR_DB.individual_type as b on a.individual_type_id_2019=b.individual_type_id;
drop table VAR_MART_DB.TEMP146;
create index I_167 on VAR_MART_DB.TEMP147(structural_variation_id_2072_key);
create table VAR_MART_DB.TEMP148 as select a.structural_variation_id_2072_key,b.structural_variation_sample_id_20138,b.individual_id_20138,b.individual_type_id_2019,b.strain_id_20138,b.description_2019,b.name_2019 from VAR_MART_DB.SPECIES_ABBREV_structvar__structural_variation__main as a left join VAR_MART_DB.TEMP147 as b on a.structural_variation_id_2072_key=b.structural_variation_id_2072_key;
drop table VAR_MART_DB.TEMP147;
alter table VAR_MART_DB.TEMP148 drop column structural_variation_sample_id_20138;
alter table VAR_MART_DB.TEMP148 drop column individual_id_20138;
alter table VAR_MART_DB.TEMP148 drop column individual_type_id_2019;
rename table VAR_MART_DB.TEMP148 to VAR_MART_DB.SPECIES_ABBREV_structvar__structural_variation_annotation__dm;
create index I_168 on VAR_MART_DB.SPECIES_ABBREV_structvar__structural_variation_annotation__dm(structural_variation_id_2072_key);
create table VAR_MART_DB.TEMP149 as select a.structural_variation_id_2072_key from VAR_MART_DB.SPECIES_ABBREV_structvar__structural_variation__main as a;
create index I_169 on VAR_MART_DB.TEMP149(structural_variation_id_2072_key);
create table VAR_MART_DB.TEMP150 as select a.*,b.variation_set_id as variation_set_id_20115 from VAR_MART_DB.TEMP149 as a inner join VAR_DB.MTMP_variation_set_structural_variation as b on a.structural_variation_id_2072_key=b.structural_variation_id;
drop table VAR_MART_DB.TEMP149;
create index I_170 on VAR_MART_DB.TEMP150(variation_set_id_20115);
create table VAR_MART_DB.TEMP151 as select a.*,b.description as description_2077,b.name as name_2077 from VAR_MART_DB.TEMP150 as a inner join VAR_DB.variation_set as b on a.variation_set_id_20115=b.variation_set_id;
drop table VAR_MART_DB.TEMP150;
create index I_171 on VAR_MART_DB.TEMP151(structural_variation_id_2072_key);
create table VAR_MART_DB.TEMP152 as select a.structural_variation_id_2072_key,b.description_2077,b.variation_set_id_20115,b.name_2077 from VAR_MART_DB.SPECIES_ABBREV_structvar__structural_variation__main as a left join VAR_MART_DB.TEMP151 as b on a.structural_variation_id_2072_key=b.structural_variation_id_2072_key;
drop table VAR_MART_DB.TEMP151;
create index I_172 on VAR_MART_DB.TEMP152(name_2077);
rename table VAR_MART_DB.TEMP152 to VAR_MART_DB.SPECIES_ABBREV_structvar__variation_set_structural_variation__dm;
create index I_173 on VAR_MART_DB.SPECIES_ABBREV_structvar__variation_set_structural_variation__dm(structural_variation_id_2072_key);
create table VAR_MART_DB.TEMP153 as select a.structural_variation_id_2072_key from VAR_MART_DB.SPECIES_ABBREV_structvar__structural_variation__main as a;
create index I_174 on VAR_MART_DB.TEMP153(structural_variation_id_2072_key);
create table VAR_MART_DB.TEMP154 as select a.*,b.inner_start as inner_start_20116,b.outer_start as outer_start_20116,b.clinical_significance as clinical_significance_20116,b.variation_name as variation_name_20116,b.strain_name as strain_name_20116,b.phenotype as phenotype_20116,b.class_name as class_name_20116,b.sample_name as sample_name_20116,b.seq_region_end as seq_region_end_20116,b.inner_end as inner_end_20116,b.seq_region_start as seq_region_start_20116,b.seq_region_name as seq_region_name_20116,b.outer_end as outer_end_20116,b.supporting_structural_variation_id as supporting_structural_variation_id_20116,b.seq_region_strand as seq_region_strand_20116 from VAR_MART_DB.TEMP153 as a inner join VAR_DB.MTMP_supporting_structural_variation as b on a.structural_variation_id_2072_key=b.structural_variation_id;
drop table VAR_MART_DB.TEMP153;
create index I_175 on VAR_MART_DB.TEMP154(structural_variation_id_2072_key);
create table VAR_MART_DB.TEMP155 as select a.structural_variation_id_2072_key,b.outer_start_20116,b.seq_region_name_20116,b.inner_end_20116,b.variation_name_20116,b.inner_start_20116,b.sample_name_20116,b.seq_region_end_20116,b.seq_region_strand_20116,b.clinical_significance_20116,b.outer_end_20116,b.supporting_structural_variation_id_20116,b.strain_name_20116,b.class_name_20116,b.seq_region_start_20116,b.phenotype_20116 from VAR_MART_DB.SPECIES_ABBREV_structvar__structural_variation__main as a left join VAR_MART_DB.TEMP154 as b on a.structural_variation_id_2072_key=b.structural_variation_id_2072_key;
drop table VAR_MART_DB.TEMP154;
rename table VAR_MART_DB.TEMP155 to VAR_MART_DB.SPECIES_ABBREV_structvar__supporting_structural_variation__dm;
create index I_176 on VAR_MART_DB.SPECIES_ABBREV_structvar__supporting_structural_variation__dm(structural_variation_id_2072_key);
create table VAR_MART_DB.TEMP156 as select a.description_2021,a.attrib_type_id_2092,a.source_id_20100,a.value_2092,a.validation_status_2072,a.class_attrib_id_2072,a.name_2021,a.study_id_2072,a.external_reference_20100,a.source_id_2072,a.structural_variation_id_2072_key,a.variation_name_2072,a.name_20100,a.description_20100 from VAR_MART_DB.SPECIES_ABBREV_structvar__structural_variation__main as a;
create index I_177 on VAR_MART_DB.TEMP156(structural_variation_id_2072_key);
create table VAR_MART_DB.TEMP157 as select a.*,b.inner_start as inner_start_20104,b.outer_start as outer_start_20104,b.seq_region_id as seq_region_id_20104,b.breakpoint_order as breakpoint_order_20104,b.source_id as source_id_20104,b.variation_set_id as variation_set_id_20104,b.seq_region_end as seq_region_end_20104,b.allele_string as allele_string_20104,b.structural_variation_feature_id as structural_variation_feature_id_20104_key,b.inner_end as inner_end_20104,b.seq_region_start as seq_region_start_20104,b.study_id as study_id_20104,b.outer_end as outer_end_20104,b.seq_region_strand as seq_region_strand_20104 from VAR_MART_DB.TEMP156 as a left join VAR_DB.structural_variation_feature as b on a.structural_variation_id_2072_key=b.structural_variation_id;
drop table VAR_MART_DB.TEMP156;
create index I_178 on VAR_MART_DB.TEMP157(seq_region_id_20104);
create table VAR_MART_DB.TEMP160 as select a.*,b.name as name_2034,b.coord_system_id as coord_system_id_2034 from VAR_MART_DB.TEMP157 as a left join VAR_DB.seq_region as b on a.seq_region_id_20104=b.seq_region_id;
drop table VAR_MART_DB.TEMP157;
alter table VAR_MART_DB.TEMP160 drop column coord_system_id_2034;
alter table VAR_MART_DB.TEMP160 drop column source_id_20104;
alter table VAR_MART_DB.TEMP160 drop column study_id_20104;
rename table VAR_MART_DB.TEMP160 to VAR_MART_DB.SPECIES_ABBREV_structvar__structural_variation_feature__main;
create index I_179 on VAR_MART_DB.SPECIES_ABBREV_structvar__structural_variation_feature__main(structural_variation_id_2072_key);
create index I_180 on VAR_MART_DB.SPECIES_ABBREV_structvar__structural_variation_feature__main(structural_variation_feature_id_20104_key);
alter table VAR_MART_DB.SPECIES_ABBREV_structvar__structural_variation__main add column (structural_variation_feature_count integer default 0);
update VAR_MART_DB.SPECIES_ABBREV_structvar__structural_variation__main a set structural_variation_feature_count=(select count(1) from VAR_MART_DB.SPECIES_ABBREV_structvar__structural_variation_feature__main b where a.structural_variation_id_2072_key=b.structural_variation_id_2072_key and not (b.description_2021 is null and b.source_id_20100 is null and b.inner_end_20104 is null and b.study_id_2072 is null and b.variation_set_id_20104 is null and b.seq_region_start_20104 is null and b.seq_region_strand_20104 is null and b.name_20100 is null and b.seq_region_id_20104 is null and b.value_2092 is null and b.outer_start_20104 is null and b.breakpoint_order_20104 is null and b.validation_status_2072 is null and b.seq_region_end_20104 is null and b.name_2034 is null and b.class_attrib_id_2072 is null and b.attrib_type_id_2092 is null and b.allele_string_20104 is null and b.variation_name_2072 is null and b.inner_start_20104 is null and b.name_2021 is null and b.structural_variation_feature_id_20104_key is null and b.external_reference_20100 is null and b.outer_end_20104 is null and b.source_id_2072 is null and b.description_20100 is null));
create index I_181 on VAR_MART_DB.SPECIES_ABBREV_structvar__structural_variation__main(structural_variation_feature_count);
alter table VAR_MART_DB.SPECIES_ABBREV_structvar__structural_variation_feature__main add column (structural_variation_feature_count integer default 0);
update VAR_MART_DB.SPECIES_ABBREV_structvar__structural_variation_feature__main a set structural_variation_feature_count=(select max(structural_variation_feature_count) from VAR_MART_DB.SPECIES_ABBREV_structvar__structural_variation__main b where a.structural_variation_id_2072_key=b.structural_variation_id_2072_key);
create index I_182 on VAR_MART_DB.SPECIES_ABBREV_structvar__structural_variation_feature__main(structural_variation_feature_count);
create table VAR_MART_DB.TEMP161 as select a.validation_status as validation_status_2072,a.variation_name as variation_name_2072,a.structural_variation_id as structural_variation_id_2072_key,a.source_id as source_id_2072,a.study_id as study_id_2072,a.class_attrib_id as class_attrib_id_2072 from VAR_DB.structural_variation as a where a.is_evidence=0 and a.somatic=1;
create index I_183 on VAR_MART_DB.TEMP161(source_id_2072);
create table VAR_MART_DB.TEMP162 as select a.*,b.description as description_2021,b.name as name_2021 from VAR_MART_DB.TEMP161 as a left join VAR_DB.source as b on a.source_id_2072=b.source_id;
drop table VAR_MART_DB.TEMP161;
create index I_184 on VAR_MART_DB.TEMP162(class_attrib_id_2072);
create table VAR_MART_DB.TEMP164 as select a.*,b.value as value_2092,b.attrib_type_id as attrib_type_id_2092 from VAR_MART_DB.TEMP162 as a left join VAR_DB.attrib as b on a.class_attrib_id_2072=b.attrib_id;
drop table VAR_MART_DB.TEMP162;
create index I_185 on VAR_MART_DB.TEMP164(attrib_type_id_2092);
create table VAR_MART_DB.TEMP165 as select a.* from VAR_MART_DB.TEMP164 as a left join VAR_DB.attrib_type as b on a.attrib_type_id_2092=b.attrib_type_id;
drop table VAR_MART_DB.TEMP164;
create index I_186 on VAR_MART_DB.TEMP165(study_id_2072);
create table VAR_MART_DB.TEMP166 as select a.*,b.external_reference as external_reference_20100,b.source_id as source_id_20100,b.description as description_20100,b.name as name_20100 from VAR_MART_DB.TEMP165 as a left join VAR_DB.study as b on a.study_id_2072=b.study_id;
drop table VAR_MART_DB.TEMP165;
create index I_187 on VAR_MART_DB.TEMP166(source_id_20100);
create table VAR_MART_DB.TEMP167 as select a.* from VAR_MART_DB.TEMP166 as a left join VAR_DB.source as b on a.source_id_20100=b.source_id;
drop table VAR_MART_DB.TEMP166;
rename table VAR_MART_DB.TEMP167 to VAR_MART_DB.SPECIES_ABBREV_structvar_som__structural_variation__main;
create index I_188 on VAR_MART_DB.SPECIES_ABBREV_structvar_som__structural_variation__main(structural_variation_id_2072_key);
create table VAR_MART_DB.TEMP169 as select a.structural_variation_id_2072_key from VAR_MART_DB.SPECIES_ABBREV_structvar_som__structural_variation__main as a;
create index I_189 on VAR_MART_DB.TEMP169(structural_variation_id_2072_key);
create table VAR_MART_DB.TEMP170 as select a.*,b.structural_variation_sample_id as structural_variation_sample_id_20138,b.strain_id as strain_id_20138,b.individual_id as individual_id_20138 from VAR_MART_DB.TEMP169 as a inner join VAR_DB.structural_variation_sample as b on a.structural_variation_id_2072_key=b.structural_variation_id;
drop table VAR_MART_DB.TEMP169;
create index I_190 on VAR_MART_DB.TEMP170(strain_id_20138);
create table VAR_MART_DB.TEMP171 as select a.*,b.individual_type_id as individual_type_id_2019,b.description as description_2019,b.name as name_2019 from VAR_MART_DB.TEMP170 as a inner join VAR_DB.individual as b on a.strain_id_20138=b.individual_id;
drop table VAR_MART_DB.TEMP170;
create index I_191 on VAR_MART_DB.TEMP171(individual_type_id_2019);
create table VAR_MART_DB.TEMP172 as select a.* from VAR_MART_DB.TEMP171 as a inner join VAR_DB.individual_type as b on a.individual_type_id_2019=b.individual_type_id;
drop table VAR_MART_DB.TEMP171;
create index I_192 on VAR_MART_DB.TEMP172(structural_variation_id_2072_key);
create table VAR_MART_DB.TEMP173 as select a.structural_variation_id_2072_key,b.structural_variation_sample_id_20138,b.individual_id_20138,b.individual_type_id_2019,b.strain_id_20138,b.description_2019,b.name_2019 from VAR_MART_DB.SPECIES_ABBREV_structvar_som__structural_variation__main as a left join VAR_MART_DB.TEMP172 as b on a.structural_variation_id_2072_key=b.structural_variation_id_2072_key;
drop table VAR_MART_DB.TEMP172;
alter table VAR_MART_DB.TEMP173 drop column individual_id_20138;
alter table VAR_MART_DB.TEMP173 drop column individual_type_id_2019;
rename table VAR_MART_DB.TEMP173 to VAR_MART_DB.SPECIES_ABBREV_structvar_som__structural_variation_annotation__dm;
create index I_193 on VAR_MART_DB.SPECIES_ABBREV_structvar_som__structural_variation_annotation__dm(structural_variation_id_2072_key);
create table VAR_MART_DB.TEMP174 as select a.structural_variation_id_2072_key from VAR_MART_DB.SPECIES_ABBREV_structvar_som__structural_variation__main as a;
create index I_194 on VAR_MART_DB.TEMP174(structural_variation_id_2072_key);
create table VAR_MART_DB.TEMP175 as select a.*,b.variation_set_id as variation_set_id_20115 from VAR_MART_DB.TEMP174 as a inner join VAR_DB.MTMP_variation_set_structural_variation as b on a.structural_variation_id_2072_key=b.structural_variation_id;
drop table VAR_MART_DB.TEMP174;
create index I_195 on VAR_MART_DB.TEMP175(variation_set_id_20115);
create table VAR_MART_DB.TEMP176 as select a.*,b.description as description_2077,b.name as name_2077,b.short_name_attrib_id as short_name_attrib_id_2077 from VAR_MART_DB.TEMP175 as a inner join VAR_DB.variation_set as b on a.variation_set_id_20115=b.variation_set_id;
drop table VAR_MART_DB.TEMP175;
create index I_196 on VAR_MART_DB.TEMP176(structural_variation_id_2072_key);
create table VAR_MART_DB.TEMP177 as select a.structural_variation_id_2072_key,b.short_name_attrib_id_2077,b.description_2077,b.variation_set_id_20115,b.name_2077 from VAR_MART_DB.SPECIES_ABBREV_structvar_som__structural_variation__main as a left join VAR_MART_DB.TEMP176 as b on a.structural_variation_id_2072_key=b.structural_variation_id_2072_key;
drop table VAR_MART_DB.TEMP176;
rename table VAR_MART_DB.TEMP177 to VAR_MART_DB.SPECIES_ABBREV_structvar_som__variation_set_structural_variation__dm;
create index I_197 on VAR_MART_DB.SPECIES_ABBREV_structvar_som__variation_set_structural_variation__dm(structural_variation_id_2072_key);
create table VAR_MART_DB.TEMP178 as select a.structural_variation_id_2072_key from VAR_MART_DB.SPECIES_ABBREV_structvar_som__structural_variation__main as a;
create index I_198 on VAR_MART_DB.TEMP178(structural_variation_id_2072_key);
create table VAR_MART_DB.TEMP179 as select a.*,b.inner_start as inner_start_20116,b.outer_start as outer_start_20116,b.clinical_significance as clinical_significance_20116,b.variation_name as variation_name_20116,b.phenotype as phenotype_20116,b.class_name as class_name_20116,b.sample_name as sample_name_20116,b.seq_region_end as seq_region_end_20116,b.inner_end as inner_end_20116,b.seq_region_start as seq_region_start_20116,b.seq_region_name as seq_region_name_20116,b.outer_end as outer_end_20116,b.supporting_structural_variation_id as supporting_structural_variation_id_20116,b.seq_region_strand as seq_region_strand_20116 from VAR_MART_DB.TEMP178 as a inner join VAR_DB.MTMP_supporting_structural_variation as b on a.structural_variation_id_2072_key=b.structural_variation_id;
drop table VAR_MART_DB.TEMP178;
create index I_199 on VAR_MART_DB.TEMP179(structural_variation_id_2072_key);
create table VAR_MART_DB.TEMP180 as select a.structural_variation_id_2072_key,b.outer_start_20116,b.seq_region_name_20116,b.inner_end_20116,b.variation_name_20116,b.inner_start_20116,b.sample_name_20116,b.seq_region_end_20116,b.seq_region_strand_20116,b.clinical_significance_20116,b.outer_end_20116,b.supporting_structural_variation_id_20116,b.class_name_20116,b.seq_region_start_20116,b.phenotype_20116 from VAR_MART_DB.SPECIES_ABBREV_structvar_som__structural_variation__main as a left join VAR_MART_DB.TEMP179 as b on a.structural_variation_id_2072_key=b.structural_variation_id_2072_key;
drop table VAR_MART_DB.TEMP179;
rename table VAR_MART_DB.TEMP180 to VAR_MART_DB.SPECIES_ABBREV_structvar_som__supporting_structural_variation__dm;
create index I_200 on VAR_MART_DB.SPECIES_ABBREV_structvar_som__supporting_structural_variation__dm(structural_variation_id_2072_key);
create table VAR_MART_DB.TEMP181 as select a.description_2021,a.attrib_type_id_2092,a.source_id_20100,a.value_2092,a.validation_status_2072,a.class_attrib_id_2072,a.name_2021,a.study_id_2072,a.external_reference_20100,a.source_id_2072,a.structural_variation_id_2072_key,a.variation_name_2072,a.name_20100,a.description_20100 from VAR_MART_DB.SPECIES_ABBREV_structvar_som__structural_variation__main as a;
create index I_201 on VAR_MART_DB.TEMP181(structural_variation_id_2072_key);
create table VAR_MART_DB.TEMP182 as select a.*,b.inner_start as inner_start_20104,b.outer_start as outer_start_20104,b.seq_region_id as seq_region_id_20104,b.breakpoint_order as breakpoint_order_20104,b.source_id as source_id_20104,b.variation_set_id as variation_set_id_20104,b.seq_region_end as seq_region_end_20104,b.allele_string as allele_string_20104,b.structural_variation_feature_id as structural_variation_feature_id_20104_key,b.inner_end as inner_end_20104,b.seq_region_start as seq_region_start_20104,b.study_id as study_id_20104,b.outer_end as outer_end_20104,b.seq_region_strand as seq_region_strand_20104 from VAR_MART_DB.TEMP181 as a left join VAR_DB.structural_variation_feature as b on a.structural_variation_id_2072_key=b.structural_variation_id;
drop table VAR_MART_DB.TEMP181;
create index I_202 on VAR_MART_DB.TEMP182(seq_region_id_20104);
create table VAR_MART_DB.TEMP185 as select a.*,b.name as name_2034,b.coord_system_id as coord_system_id_2034 from VAR_MART_DB.TEMP182 as a left join VAR_DB.seq_region as b on a.seq_region_id_20104=b.seq_region_id;
drop table VAR_MART_DB.TEMP182;
alter table VAR_MART_DB.TEMP185 drop column coord_system_id_2034;
alter table VAR_MART_DB.TEMP185 drop column source_id_20104;
alter table VAR_MART_DB.TEMP185 drop column study_id_20104;
rename table VAR_MART_DB.TEMP185 to VAR_MART_DB.SPECIES_ABBREV_structvar_som__structural_variation_feature__main;
create index I_203 on VAR_MART_DB.SPECIES_ABBREV_structvar_som__structural_variation_feature__main(structural_variation_id_2072_key);
create index I_204 on VAR_MART_DB.SPECIES_ABBREV_structvar_som__structural_variation_feature__main(structural_variation_feature_id_20104_key);
alter table VAR_MART_DB.SPECIES_ABBREV_structvar_som__structural_variation__main add column (structural_variation_feature_count integer default 0);
update VAR_MART_DB.SPECIES_ABBREV_structvar_som__structural_variation__main a set structural_variation_feature_count=(select count(1) from VAR_MART_DB.SPECIES_ABBREV_structvar_som__structural_variation_feature__main b where a.structural_variation_id_2072_key=b.structural_variation_id_2072_key and not (b.description_2021 is null and b.source_id_20100 is null and b.inner_end_20104 is null and b.study_id_2072 is null and b.variation_set_id_20104 is null and b.seq_region_start_20104 is null and b.seq_region_strand_20104 is null and b.name_20100 is null and b.seq_region_id_20104 is null and b.value_2092 is null and b.outer_start_20104 is null and b.breakpoint_order_20104 is null and b.validation_status_2072 is null and b.seq_region_end_20104 is null and b.name_2034 is null and b.class_attrib_id_2072 is null and b.attrib_type_id_2092 is null and b.allele_string_20104 is null and b.variation_name_2072 is null and b.inner_start_20104 is null and b.name_2021 is null and b.structural_variation_feature_id_20104_key is null and b.external_reference_20100 is null and b.outer_end_20104 is null and b.source_id_2072 is null and b.description_20100 is null));
create index I_205 on VAR_MART_DB.SPECIES_ABBREV_structvar_som__structural_variation__main(structural_variation_feature_count);
alter table VAR_MART_DB.SPECIES_ABBREV_structvar_som__structural_variation_feature__main add column (structural_variation_feature_count integer default 0);
update VAR_MART_DB.SPECIES_ABBREV_structvar_som__structural_variation_feature__main a set structural_variation_feature_count=(select max(structural_variation_feature_count) from VAR_MART_DB.SPECIES_ABBREV_structvar_som__structural_variation__main b where a.structural_variation_id_2072_key=b.structural_variation_id_2072_key);
create index I_206 on VAR_MART_DB.SPECIES_ABBREV_structvar_som__structural_variation_feature__main(structural_variation_feature_count);
