create table VAR_MART_DB.TEMP0 as select a.clinical_significance as clinical_significance_2025,a.minor_allele_freq as minor_allele_freq_2025,a.source_id as source_id_2025,a.name as name_2025,a.ancestral_allele as ancestral_allele_2025,a.evidence as evidence_2025,a.minor_allele as minor_allele_2025,a.variation_id as variation_id_2025_key,a.minor_allele_count as minor_allele_count_2025 from VAR_DB.variation as a where a.somatic=0;
create index I_0 on VAR_MART_DB.TEMP0(source_id_2025);
create table VAR_MART_DB.TEMP1 as select a.*,b.description as description_2021,b.name as name_2021 from VAR_MART_DB.TEMP0 as a left join VAR_DB.source as b on a.source_id_2025=b.source_id;
drop table VAR_MART_DB.TEMP0;
alter table VAR_MART_DB.TEMP1 drop column source_id_2025;
create index I_1 on VAR_MART_DB.TEMP1(name_2025);
create index I_2 on VAR_MART_DB.TEMP1(name_2021);
create index I_3 on VAR_MART_DB.TEMP1(evidence_2025);
rename table VAR_MART_DB.TEMP1 to VAR_MART_DB.SPECIES_ABBREV_snp__variation__main;
create index I_4 on VAR_MART_DB.SPECIES_ABBREV_snp__variation__main(variation_id_2025_key);
create table VAR_MART_DB.TEMP2 as select a.source_id as source_id_2021,a.description as description_2021,a.name as name_2021 from VAR_DB.source as a;
create index I_5 on VAR_MART_DB.TEMP2(source_id_2021);
create table VAR_MART_DB.TEMP3 as select a.*,b.subsnp_id as subsnp_id_2030,b.name as name_2030,b.variation_id as variation_id_2025_key,b.variation_synonym_id as variation_synonym_id_2030 from VAR_MART_DB.TEMP2 as a inner join VAR_DB.variation_synonym as b on a.source_id_2021=b.source_id;
drop table VAR_MART_DB.TEMP2;
create index I_6 on VAR_MART_DB.TEMP3(variation_id_2025_key);
create table VAR_MART_DB.TEMP5 as select a.* from VAR_MART_DB.TEMP3 as a inner join VAR_MART_DB.SPECIES_ABBREV_snp__variation__main as b on a.variation_id_2025_key=b.variation_id_2025_key;
drop table VAR_MART_DB.TEMP3;
create index I_7 on VAR_MART_DB.TEMP5(variation_id_2025_key);
create table VAR_MART_DB.TEMP6 as select a.variation_id_2025_key,b.source_id_2021,b.description_2021,b.variation_synonym_id_2030,b.name_2030,b.name_2021,b.subsnp_id_2030 from VAR_MART_DB.SPECIES_ABBREV_snp__variation__main as a left join VAR_MART_DB.TEMP5 as b on a.variation_id_2025_key=b.variation_id_2025_key;
drop table VAR_MART_DB.TEMP5;
alter table VAR_MART_DB.TEMP6 drop column variation_synonym_id_2030;
alter table VAR_MART_DB.TEMP6 drop column subsnp_id_2030;
create index I_8 on VAR_MART_DB.TEMP6(name_2030);
create index I_9 on VAR_MART_DB.TEMP6(name_2021);
rename table VAR_MART_DB.TEMP6 to VAR_MART_DB.SPECIES_ABBREV_snp__variation_synonym__dm;
create index I_10 on VAR_MART_DB.SPECIES_ABBREV_snp__variation_synonym__dm(variation_id_2025_key);
create table VAR_MART_DB.TEMP7 as select a.variation_id_2025_key from VAR_MART_DB.SPECIES_ABBREV_snp__variation__main as a;
create index I_11 on VAR_MART_DB.TEMP7(variation_id_2025_key);
create table VAR_MART_DB.TEMP8 as select a.*,b.subsnp_id as subsnp_id_2023,b.allele_1 as allele_1_2023,b.allele_2 as allele_2_2023,b.individual_id as individual_id_2023 from VAR_MART_DB.TEMP7 as a left join VAR_DB.tmp_individual_genotype_single_bp as b on a.variation_id_2025_key=b.variation_id;
drop table VAR_MART_DB.TEMP7;
create index I_12 on VAR_MART_DB.TEMP8(individual_id_2023);
create table VAR_MART_DB.TEMP10 as select a.*,b.individual_type_id as individual_type_id_2019,b.name as name_2019 from VAR_MART_DB.TEMP8 as a inner join VAR_DB.individual as b on a.individual_id_2023=b.individual_id and (b.display in ("REFERENCE","DEFAULT","DISPLAYABLE","MARTDISPLAYABLE"));
drop table VAR_MART_DB.TEMP8;
create index I_13 on VAR_MART_DB.TEMP10(individual_type_id_2019);
create table VAR_MART_DB.TEMP12 as select a.* from VAR_MART_DB.TEMP10 as a left join VAR_DB.individual_type as b on a.individual_type_id_2019=b.individual_type_id;
drop table VAR_MART_DB.TEMP10;
create table VAR_MART_DB.TEMP13 as select individual_id_2023,individual_type_id_2019,name_2019,allele_2_2023,variation_id_2025_key,subsnp_id_2023,allele_1_2023,concat(allele_1_2023, '|', allele_2_2023) as allele from VAR_MART_DB.TEMP12;
drop table VAR_MART_DB.TEMP12;
create index I_14 on VAR_MART_DB.TEMP13(variation_id_2025_key);
create table VAR_MART_DB.TEMP14 as select a.variation_id_2025_key,b.individual_id_2023,b.subsnp_id_2023,b.individual_type_id_2019,b.allele,b.allele_2_2023,b.allele_1_2023,b.name_2019 from VAR_MART_DB.SPECIES_ABBREV_snp__variation__main as a left join VAR_MART_DB.TEMP13 as b on a.variation_id_2025_key=b.variation_id_2025_key;
drop table VAR_MART_DB.TEMP13;
create table VAR_MART_DB.TEMP15 as select distinct individual_id_2023,name_2019,allele,variation_id_2025_key from VAR_MART_DB.TEMP14;
drop table VAR_MART_DB.TEMP14;
create index I_15 on VAR_MART_DB.TEMP15(name_2019);
rename table VAR_MART_DB.TEMP15 to VAR_MART_DB.SPECIES_ABBREV_snp__poly__dm;
create index I_16 on VAR_MART_DB.SPECIES_ABBREV_snp__poly__dm(variation_id_2025_key);
create table VAR_MART_DB.TEMP16 as select a.variation_id_2025_key from VAR_MART_DB.SPECIES_ABBREV_snp__variation__main as a;
create index I_17 on VAR_MART_DB.TEMP16(variation_id_2025_key);
create table VAR_MART_DB.TEMP17 as select a.*,b.population_genotype_id as population_genotype_id_20107,b.allele_1 as allele_1_20107,b.population_id as population_id_20107,b.allele_2 as allele_2_20107,b.frequency as frequency_2016 from VAR_MART_DB.TEMP16 as a inner join VAR_DB.MTMP_population_genotype as b on a.variation_id_2025_key=b.variation_id;
drop table VAR_MART_DB.TEMP16;
create index I_18 on VAR_MART_DB.TEMP17(population_id_20107);
create table VAR_MART_DB.TEMP18 as select a.*,b.name as name_2019,b.size as size_2019 from VAR_MART_DB.TEMP17 as a inner join VAR_DB.population as b on a.population_id_20107=b.population_id;
drop table VAR_MART_DB.TEMP17;
create table VAR_MART_DB.TEMP19 as select name_2019,frequency_2016,size_2019,allele_2_20107,population_id_20107,variation_id_2025_key,allele_1_20107,population_genotype_id_20107,concat(allele_1_20107, '|', allele_2_20107) as allele from VAR_MART_DB.TEMP18;
drop table VAR_MART_DB.TEMP18;
create index I_19 on VAR_MART_DB.TEMP19(variation_id_2025_key);
create table VAR_MART_DB.TEMP20 as select a.variation_id_2025_key,b.name_2019,b.allele_1_20107,b.population_id_20107,b.allele,b.population_genotype_id_20107,b.size_2019,b.allele_2_20107,b.frequency_2016 from VAR_MART_DB.SPECIES_ABBREV_snp__variation__main as a left join VAR_MART_DB.TEMP19 as b on a.variation_id_2025_key=b.variation_id_2025_key;
drop table VAR_MART_DB.TEMP19;
alter table VAR_MART_DB.TEMP20 drop column allele_1_20107;
alter table VAR_MART_DB.TEMP20 drop column population_id_20107;
alter table VAR_MART_DB.TEMP20 drop column population_genotype_id_20107;
alter table VAR_MART_DB.TEMP20 drop column allele_2_20107;
rename table VAR_MART_DB.TEMP20 to VAR_MART_DB.SPECIES_ABBREV_snp__population_genotype__dm;
create index I_20 on VAR_MART_DB.SPECIES_ABBREV_snp__population_genotype__dm(variation_id_2025_key);
create table VAR_MART_DB.TEMP21 as select a.variation_id_2025_key from VAR_MART_DB.SPECIES_ABBREV_snp__variation__main as a;
create index I_21 on VAR_MART_DB.TEMP21(variation_id_2025_key);
create table VAR_MART_DB.TEMP22 as select a.*,b.variation_set_id as variation_set_id_2078 from VAR_MART_DB.TEMP21 as a inner join VAR_DB.MTMP_variation_set_variation as b on a.variation_id_2025_key=b.variation_id;
drop table VAR_MART_DB.TEMP21;
create index I_22 on VAR_MART_DB.TEMP22(variation_set_id_2078);
create table VAR_MART_DB.TEMP23 as select a.*,b.description as description_2077,b.name as name_2077 from VAR_MART_DB.TEMP22 as a inner join VAR_DB.variation_set as b on a.variation_set_id_2078=b.variation_set_id;
drop table VAR_MART_DB.TEMP22;
create index I_23 on VAR_MART_DB.TEMP23(variation_id_2025_key);
create table VAR_MART_DB.TEMP24 as select a.variation_id_2025_key,b.variation_set_id_2078,b.description_2077,b.name_2077 from VAR_MART_DB.SPECIES_ABBREV_snp__variation__main as a left join VAR_MART_DB.TEMP23 as b on a.variation_id_2025_key=b.variation_id_2025_key;
drop table VAR_MART_DB.TEMP23;
create index I_24 on VAR_MART_DB.TEMP24(name_2077);
rename table VAR_MART_DB.TEMP24 to VAR_MART_DB.SPECIES_ABBREV_snp__variation_set_variation__dm;
create index I_25 on VAR_MART_DB.SPECIES_ABBREV_snp__variation_set_variation__dm(variation_id_2025_key);
create table VAR_MART_DB.TEMP25 as select a.variation_id_2025_key from VAR_MART_DB.SPECIES_ABBREV_snp__variation__main as a;
create index I_26 on VAR_MART_DB.TEMP25(variation_id_2025_key);
create table VAR_MART_DB.TEMP26 as select a.*,b.subsnp_id as subsnp_id_2010,b.allele_1 as allele_1_2010,b.allele_2 as allele_2_2010,b.individual_id as individual_id_2010 from VAR_MART_DB.TEMP25 as a left join VAR_DB.individual_genotype_multiple_bp as b on a.variation_id_2025_key=b.variation_id;
drop table VAR_MART_DB.TEMP25;
create index I_27 on VAR_MART_DB.TEMP26(individual_id_2010);
create table VAR_MART_DB.TEMP28 as select a.*,b.individual_type_id as individual_type_id_2019,b.name as name_2019 from VAR_MART_DB.TEMP26 as a inner join VAR_DB.individual as b on a.individual_id_2010=b.individual_id and (b.display in ("REFERENCE","DEFAULT","DISPLAYABLE","MARTDISPLAYABLE"));
drop table VAR_MART_DB.TEMP26;
create index I_28 on VAR_MART_DB.TEMP28(individual_type_id_2019);
create table VAR_MART_DB.TEMP30 as select a.* from VAR_MART_DB.TEMP28 as a left join VAR_DB.individual_type as b on a.individual_type_id_2019=b.individual_type_id;
drop table VAR_MART_DB.TEMP28;
create table VAR_MART_DB.TEMP31 as select individual_type_id_2019,name_2019,individual_id_2010,allele_2_2010,variation_id_2025_key,subsnp_id_2010,allele_1_2010,concat(allele_1_2010, '|', allele_2_2010) as allele from VAR_MART_DB.TEMP30;
drop table VAR_MART_DB.TEMP30;
create index I_29 on VAR_MART_DB.TEMP31(variation_id_2025_key);
create table VAR_MART_DB.TEMP32 as select a.variation_id_2025_key,b.individual_id_2010,b.individual_type_id_2019,b.allele_2_2010,b.allele_1_2010,b.allele,b.subsnp_id_2010,b.name_2019 from VAR_MART_DB.SPECIES_ABBREV_snp__variation__main as a left join VAR_MART_DB.TEMP31 as b on a.variation_id_2025_key=b.variation_id_2025_key;
drop table VAR_MART_DB.TEMP31;
create table VAR_MART_DB.TEMP33 as select distinct name_2019,individual_id_2010,allele,variation_id_2025_key from VAR_MART_DB.TEMP32;
drop table VAR_MART_DB.TEMP32;
create index I_30 on VAR_MART_DB.TEMP33(name_2019);
rename table VAR_MART_DB.TEMP33 to VAR_MART_DB.SPECIES_ABBREV_snp__mpoly__dm;
create index I_31 on VAR_MART_DB.SPECIES_ABBREV_snp__mpoly__dm(variation_id_2025_key);
create table VAR_MART_DB.TEMP34 as select a.variation_id_2025_key from VAR_MART_DB.SPECIES_ABBREV_snp__variation__main as a;
create index I_32 on VAR_MART_DB.TEMP34(variation_id_2025_key);
create table VAR_MART_DB.TEMP35 as select a.*,b.risk_allele as associated_variant_risk_allele_2035,b.study_id as study_id_2035,b.is_significant as is_significant_20133,b.associated_gene as associated_gene_2035,b.p_value as p_value_2035,b.variation_names as variation_names_2035,b.phenotype_id as phenotype_id_2035 from VAR_MART_DB.TEMP34 as a inner join VAR_DB.MTMP_variation_annotation as b on a.variation_id_2025_key=b.variation_id;
drop table VAR_MART_DB.TEMP34;
create index I_33 on VAR_MART_DB.TEMP35(phenotype_id_2035);
create table VAR_MART_DB.TEMP36 as select a.*,b.stable_id as stable_id_2033,b.description as description_2033 from VAR_MART_DB.TEMP35 as a inner join VAR_DB.phenotype as b on a.phenotype_id_2035=b.phenotype_id;
drop table VAR_MART_DB.TEMP35;
create index I_34 on VAR_MART_DB.TEMP36(study_id_2035);
create table VAR_MART_DB.TEMP37 as select a.*,b.external_reference as external_reference_20100,b.source_id as source_id_20100,b.description as description_20100,b.study_type as study_type_20100 from VAR_MART_DB.TEMP36 as a left join VAR_DB.study as b on a.study_id_2035=b.study_id;
drop table VAR_MART_DB.TEMP36;
create index I_35 on VAR_MART_DB.TEMP37(source_id_20100);
create table VAR_MART_DB.TEMP38 as select a.*,b.name as name_2021 from VAR_MART_DB.TEMP37 as a left join VAR_DB.source as b on a.source_id_20100=b.source_id;
drop table VAR_MART_DB.TEMP37;
create index I_36 on VAR_MART_DB.TEMP38(variation_id_2025_key);
create table VAR_MART_DB.TEMP39 as select a.variation_id_2025_key,b.associated_variant_risk_allele_2035,b.is_significant_20133,b.source_id_20100,b.stable_id_2033,b.associated_gene_2035,b.external_reference_20100,b.description_20100,b.phenotype_id_2035,b.study_type_20100,b.description_2033,b.name_2021,b.study_id_2035,b.p_value_2035,b.variation_names_2035 from VAR_MART_DB.SPECIES_ABBREV_snp__variation__main as a left join VAR_MART_DB.TEMP38 as b on a.variation_id_2025_key=b.variation_id_2025_key;
drop table VAR_MART_DB.TEMP38;
alter table VAR_MART_DB.TEMP39 drop column phenotype_id_2035;
create index I_37 on VAR_MART_DB.TEMP39(study_type_20100);
create index I_38 on VAR_MART_DB.TEMP39(description_2033);
rename table VAR_MART_DB.TEMP39 to VAR_MART_DB.SPECIES_ABBREV_snp__variation_annotation__dm;
create index I_39 on VAR_MART_DB.SPECIES_ABBREV_snp__variation_annotation__dm(variation_id_2025_key);
alter table VAR_MART_DB.SPECIES_ABBREV_snp__variation__main add column (variation_annotation_bool integer default 0);
update VAR_MART_DB.SPECIES_ABBREV_snp__variation__main a set variation_annotation_bool=(select case count(1) when 0 then null else 1 end from VAR_MART_DB.SPECIES_ABBREV_snp__variation_annotation__dm b where a.variation_id_2025_key=b.variation_id_2025_key and not (b.associated_variant_risk_allele_2035 is null and b.is_significant_20133 is null and b.source_id_20100 is null and b.stable_id_2033 is null and b.associated_gene_2035 is null and b.external_reference_20100 is null and b.description_20100 is null and b.study_type_20100 is null and b.description_2033 is null and b.name_2021 is null and b.study_id_2035 is null and b.p_value_2035 is null and b.variation_names_2035 is null));
create index I_40 on VAR_MART_DB.SPECIES_ABBREV_snp__variation__main(variation_annotation_bool);
create table VAR_MART_DB.TEMP40 as select a.variation_id_2025_key from VAR_MART_DB.SPECIES_ABBREV_snp__variation__main as a;
create index I_41 on VAR_MART_DB.TEMP40(variation_id_2025_key);
create table VAR_MART_DB.TEMP41 as select a.*,b.publication_id as publication_id_20139 from VAR_MART_DB.TEMP40 as a inner join VAR_DB.variation_citation as b on a.variation_id_2025_key=b.variation_id;
drop table VAR_MART_DB.TEMP40;
create index I_42 on VAR_MART_DB.TEMP41(publication_id_20139);
create table VAR_MART_DB.TEMP42 as select a.*,b.pmcid as pmcid_20137,b.authors as authors_20137,b.title as title_20137,b.pmid as pmid_20137,b.year as year_20137,b.ucsc_id as ucsc_id_20137,b.doi as doi_20137 from VAR_MART_DB.TEMP41 as a inner join VAR_DB.publication as b on a.publication_id_20139=b.publication_id;
drop table VAR_MART_DB.TEMP41;
create index I_43 on VAR_MART_DB.TEMP42(variation_id_2025_key);
create table VAR_MART_DB.TEMP43 as select a.variation_id_2025_key,b.ucsc_id_20137,b.title_20137,b.pmcid_20137,b.doi_20137,b.publication_id_20139,b.authors_20137,b.year_20137,b.pmid_20137 from VAR_MART_DB.SPECIES_ABBREV_snp__variation__main as a left join VAR_MART_DB.TEMP42 as b on a.variation_id_2025_key=b.variation_id_2025_key;
drop table VAR_MART_DB.TEMP42;
rename table VAR_MART_DB.TEMP43 to VAR_MART_DB.SPECIES_ABBREV_snp__variation_citation__dm;
create index I_44 on VAR_MART_DB.SPECIES_ABBREV_snp__variation_citation__dm(variation_id_2025_key);
alter table VAR_MART_DB.SPECIES_ABBREV_snp__variation__main add column (variation_citation_bool integer default 0);
update VAR_MART_DB.SPECIES_ABBREV_snp__variation__main a set variation_citation_bool=(select case count(1) when 0 then null else 1 end from VAR_MART_DB.SPECIES_ABBREV_snp__variation_citation__dm b where a.variation_id_2025_key=b.variation_id_2025_key and not (b.ucsc_id_20137 is null and b.title_20137 is null and b.pmcid_20137 is null and b.doi_20137 is null and b.publication_id_20139 is null and b.authors_20137 is null and b.year_20137 is null and b.pmid_20137 is null));
create index I_45 on VAR_MART_DB.SPECIES_ABBREV_snp__variation__main(variation_citation_bool);
create table VAR_MART_DB.TEMP44 as select a.variation_id_2025_key from VAR_MART_DB.SPECIES_ABBREV_snp__variation__main as a;
create index I_46 on VAR_MART_DB.TEMP44(variation_id_2025_key);
create table VAR_MART_DB.TEMP45 as select a.*,b.sample_name as sample_name_2085 from VAR_MART_DB.TEMP44 as a inner join VAR_DB.strain_gtype_poly as b on a.variation_id_2025_key=b.variation_id;
drop table VAR_MART_DB.TEMP44;
create index I_47 on VAR_MART_DB.TEMP45(variation_id_2025_key);
create table VAR_MART_DB.TEMP46 as select a.variation_id_2025_key,b.sample_name_2085 from VAR_MART_DB.SPECIES_ABBREV_snp__variation__main as a left join VAR_MART_DB.TEMP45 as b on a.variation_id_2025_key=b.variation_id_2025_key;
drop table VAR_MART_DB.TEMP45;
rename table VAR_MART_DB.TEMP46 to VAR_MART_DB.SPECIES_ABBREV_snp__strain_gtype_poly__dm;
create index I_48 on VAR_MART_DB.SPECIES_ABBREV_snp__strain_gtype_poly__dm(variation_id_2025_key);
create table VAR_MART_DB.TEMP47 as select a.description_2021,a.minor_allele_freq_2025,a.variation_citation_bool,a.minor_allele_2025,a.minor_allele_count_2025,a.name_2021,a.ancestral_allele_2025,a.clinical_significance_2025,a.variation_annotation_bool,a.variation_id_2025_key,a.name_2025,a.evidence_2025 from VAR_MART_DB.SPECIES_ABBREV_snp__variation__main as a;
create index I_49 on VAR_MART_DB.TEMP47(variation_id_2025_key);
create table VAR_MART_DB.TEMP48 as select a.*,b.variation_feature_id as variation_feature_id_2026_key,b.seq_region_id as seq_region_id_2026,b.clinical_significance as clinical_significance_2026,b.seq_region_start as seq_region_start_2026,b.variation_name as variation_name_2026,b.source_id as source_id_2026,b.map_weight as map_weight_2026,b.variation_set_id as variation_set_id_2026,b.seq_region_strand as seq_region_strand_2026,b.seq_region_end as seq_region_end_2026,b.allele_string as allele_string_2026 from VAR_MART_DB.TEMP47 as a left join VAR_DB.variation_feature as b on a.variation_id_2025_key=b.variation_id;
drop table VAR_MART_DB.TEMP47;
create index I_50 on VAR_MART_DB.TEMP48(source_id_2026);
create table VAR_MART_DB.TEMP49 as select a.* from VAR_MART_DB.TEMP48 as a left join VAR_DB.source as b on a.source_id_2026=b.source_id;
drop table VAR_MART_DB.TEMP48;
create index I_51 on VAR_MART_DB.TEMP49(seq_region_id_2026);
create table VAR_MART_DB.TEMP50 as select a.*,b.name as name_1059,b.coord_system_id as coord_system_id_1059 from VAR_MART_DB.TEMP49 as a left join CORE_DB.seq_region as b on a.seq_region_id_2026=b.seq_region_id;
drop table VAR_MART_DB.TEMP49;
create index I_52 on VAR_MART_DB.TEMP50(seq_region_id_2026);
create table VAR_MART_DB.TEMP52 as select a.*,b.coord_system_id as coord_system_id_2034 from VAR_MART_DB.TEMP50 as a left join VAR_DB.seq_region as b on a.seq_region_id_2026=b.seq_region_id;
drop table VAR_MART_DB.TEMP50;
create index I_53 on VAR_MART_DB.TEMP52(variation_set_id_2026);
create table VAR_MART_DB.TEMP53 as select a.* from VAR_MART_DB.TEMP52 as a left join VAR_DB.variation_set as b on a.variation_set_id_2026=b.variation_set_id;
drop table VAR_MART_DB.TEMP52;
alter table VAR_MART_DB.TEMP53 drop column coord_system_id_2034;
alter table VAR_MART_DB.TEMP53 drop column coord_system_id_1059;
alter table VAR_MART_DB.TEMP53 drop column source_id_2026;
create index I_54 on VAR_MART_DB.TEMP53(seq_region_start_2026);
create index I_55 on VAR_MART_DB.TEMP53(name_1059);
create index I_56 on VAR_MART_DB.TEMP53(name_2025);
rename table VAR_MART_DB.TEMP53 to VAR_MART_DB.SPECIES_ABBREV_snp__variation_feature__main;
create index I_57 on VAR_MART_DB.SPECIES_ABBREV_snp__variation_feature__main(variation_id_2025_key);
create index I_58 on VAR_MART_DB.SPECIES_ABBREV_snp__variation_feature__main(variation_feature_id_2026_key);
alter table VAR_MART_DB.SPECIES_ABBREV_snp__variation__main add column (variation_feature_count integer default 0);
update VAR_MART_DB.SPECIES_ABBREV_snp__variation__main a set variation_feature_count=(select count(1) from VAR_MART_DB.SPECIES_ABBREV_snp__variation_feature__main b where a.variation_id_2025_key=b.variation_id_2025_key and not (b.description_2021 is null and b.clinical_significance_2026 is null and b.seq_region_start_2026 is null and b.clinical_significance_2025 is null and b.variation_feature_id_2026_key is null and b.variation_set_id_2026 is null and b.allele_string_2026 is null and b.minor_allele_2025 is null and b.name_1059 is null and b.ancestral_allele_2025 is null and b.evidence_2025 is null and b.minor_allele_freq_2025 is null and b.name_2021 is null and b.seq_region_id_2026 is null and b.name_2025 is null and b.seq_region_end_2026 is null and b.seq_region_strand_2026 is null and b.minor_allele_count_2025 is null and b.variation_name_2026 is null and b.map_weight_2026 is null));
create index I_59 on VAR_MART_DB.SPECIES_ABBREV_snp__variation__main(variation_feature_count);
alter table VAR_MART_DB.SPECIES_ABBREV_snp__variation_feature__main add column (variation_feature_count integer default 0);
update VAR_MART_DB.SPECIES_ABBREV_snp__variation_feature__main a set variation_feature_count=(select max(variation_feature_count) from VAR_MART_DB.SPECIES_ABBREV_snp__variation__main b where a.variation_id_2025_key=b.variation_id_2025_key);
create index I_60 on VAR_MART_DB.SPECIES_ABBREV_snp__variation_feature__main(variation_feature_count);
create table VAR_MART_DB.TEMP54 as select a.variation_feature_id_2026_key from VAR_MART_DB.SPECIES_ABBREV_snp__variation_feature__main as a;
create index I_61 on VAR_MART_DB.TEMP54(variation_feature_id_2026_key);
create table VAR_MART_DB.TEMP55 as select a.*,b.feature_stable_id as feature_stable_id_20126,b.consequence_types as consequence_types_20126,b.allele_string as allele_string_20126 from VAR_MART_DB.TEMP54 as a inner join VAR_DB.MTMP_regulatory_feature_variation as b on a.variation_feature_id_2026_key=b.variation_feature_id;
drop table VAR_MART_DB.TEMP54;
create index I_62 on VAR_MART_DB.TEMP55(variation_feature_id_2026_key);
create table VAR_MART_DB.TEMP56 as select a.variation_feature_id_2026_key,b.feature_stable_id_20126,b.allele_string_20126,b.consequence_types_20126 from VAR_MART_DB.SPECIES_ABBREV_snp__variation_feature__main as a left join VAR_MART_DB.TEMP55 as b on a.variation_feature_id_2026_key=b.variation_feature_id_2026_key;
drop table VAR_MART_DB.TEMP55;
create index I_63 on VAR_MART_DB.TEMP56(feature_stable_id_20126);
rename table VAR_MART_DB.TEMP56 to VAR_MART_DB.SPECIES_ABBREV_snp__regulatory_feature_variation__dm;
create index I_64 on VAR_MART_DB.SPECIES_ABBREV_snp__regulatory_feature_variation__dm(variation_feature_id_2026_key);
create table VAR_MART_DB.TEMP57 as select a.variation_feature_id_2026_key from VAR_MART_DB.SPECIES_ABBREV_snp__variation_feature__main as a;
create index I_65 on VAR_MART_DB.TEMP57(variation_feature_id_2026_key);
create table VAR_MART_DB.TEMP58 as select a.*,b.feature_stable_id as feature_stable_id_20125,b.motif_name as motif_name_20125,b.in_informative_position as in_informative_position_20125,b.motif_score_delta as motif_score_delta_20125,b.consequence_types as consequence_types_20125,b.motif_start as motif_start_20125,b.allele_string as allele_string_20125 from VAR_MART_DB.TEMP57 as a inner join VAR_DB.MTMP_motif_feature_variation as b on a.variation_feature_id_2026_key=b.variation_feature_id;
drop table VAR_MART_DB.TEMP57;
create index I_66 on VAR_MART_DB.TEMP58(variation_feature_id_2026_key);
create table VAR_MART_DB.TEMP59 as select a.variation_feature_id_2026_key,b.allele_string_20125,b.motif_score_delta_20125,b.motif_name_20125,b.motif_start_20125,b.feature_stable_id_20125,b.consequence_types_20125,b.in_informative_position_20125 from VAR_MART_DB.SPECIES_ABBREV_snp__variation_feature__main as a left join VAR_MART_DB.TEMP58 as b on a.variation_feature_id_2026_key=b.variation_feature_id_2026_key;
drop table VAR_MART_DB.TEMP58;
rename table VAR_MART_DB.TEMP59 to VAR_MART_DB.SPECIES_ABBREV_snp__motif_feature_variation__dm;
create index I_67 on VAR_MART_DB.SPECIES_ABBREV_snp__motif_feature_variation__dm(variation_feature_id_2026_key);
create table VAR_MART_DB.TEMP60 as select a.seq_region_id as seq_region_id_1020,a.stable_id as stable_id_1023,a.analysis_id as analysis_id_1020,a.gene_id as gene_id_1020 from CORE_DB.gene as a;
create index I_68 on VAR_MART_DB.TEMP60(gene_id_1020);
create table VAR_MART_DB.TEMP63 as select a.*,b.transcript_id as transcript_id_1064,b.seq_region_id as seq_region_id_1064,b.stable_id as stable_id_1066,b.analysis_id as analysis_id_1064,b.biotype as biotype_1064,b.seq_region_strand as seq_region_strand_1064 from VAR_MART_DB.TEMP60 as a inner join CORE_DB.transcript as b on a.gene_id_1020=b.gene_id;
drop table VAR_MART_DB.TEMP60;
create index I_69 on VAR_MART_DB.TEMP63(stable_id_1066);
create table VAR_MART_DB.TEMP66 as select a.*,b.polyphen_prediction as polyphen_prediction_2090,b.cds_end as cds_end_2090,b.pep_allele_string as pep_allele_string_2090,b.cdna_end as cdna_end_2090,b.cds_start as cds_start_2090,b.sift_prediction as sift_prediction_2090,b.cdna_start as cdna_start_2090,b.allele_string as allele_string_2090,b.sift_score as sift_score_2090,b.variation_feature_id as variation_feature_id_2026_key,b.distance_to_transcript as distance_to_transcript_2090,b.consequence_types as consequence_types_2090,b.polyphen_score as polyphen_score_2090,b.translation_end as translation_end_2090,b.translation_start as translation_start_2090 from VAR_MART_DB.TEMP63 as a inner join VAR_DB.MTMP_transcript_variation as b on a.stable_id_1066=b.feature_stable_id;
drop table VAR_MART_DB.TEMP63;
create index I_70 on VAR_MART_DB.TEMP66(variation_feature_id_2026_key);
create table VAR_MART_DB.TEMP67 as select a.* from VAR_MART_DB.TEMP66 as a inner join VAR_MART_DB.SPECIES_ABBREV_snp__variation_feature__main as b on a.variation_feature_id_2026_key=b.variation_feature_id_2026_key;
drop table VAR_MART_DB.TEMP66;
create index I_71 on VAR_MART_DB.TEMP67(variation_feature_id_2026_key);
create table VAR_MART_DB.TEMP68 as select a.variation_feature_id_2026_key,b.allele_string_2090,b.stable_id_1066,b.sift_prediction_2090,b.distance_to_transcript_2090,b.cds_start_2090,b.stable_id_1023,b.cdna_end_2090,b.transcript_id_1064,b.gene_id_1020,b.polyphen_prediction_2090,b.translation_end_2090,b.sift_score_2090,b.cdna_start_2090,b.translation_start_2090,b.cds_end_2090,b.seq_region_id_1020,b.consequence_types_2090,b.seq_region_strand_1064,b.seq_region_id_1064,b.analysis_id_1064,b.polyphen_score_2090,b.pep_allele_string_2090,b.analysis_id_1020,b.biotype_1064 from VAR_MART_DB.SPECIES_ABBREV_snp__variation_feature__main as a left join VAR_MART_DB.TEMP67 as b on a.variation_feature_id_2026_key=b.variation_feature_id_2026_key;
drop table VAR_MART_DB.TEMP67;
alter table VAR_MART_DB.TEMP68 drop column transcript_id_1064;
alter table VAR_MART_DB.TEMP68 drop column seq_region_id_1020;
alter table VAR_MART_DB.TEMP68 drop column seq_region_id_1064;
alter table VAR_MART_DB.TEMP68 drop column analysis_id_1064;
alter table VAR_MART_DB.TEMP68 drop column analysis_id_1020;
create index I_72 on VAR_MART_DB.TEMP68(stable_id_1066);
create index I_73 on VAR_MART_DB.TEMP68(sift_prediction_2090);
create index I_74 on VAR_MART_DB.TEMP68(stable_id_1023);
create index I_75 on VAR_MART_DB.TEMP68(polyphen_prediction_2090);
create index I_76 on VAR_MART_DB.TEMP68(cdna_start_2090);
create index I_77 on VAR_MART_DB.TEMP68(translation_start_2090);
create index I_78 on VAR_MART_DB.TEMP68(consequence_types_2090);
rename table VAR_MART_DB.TEMP68 to VAR_MART_DB.SPECIES_ABBREV_snp__mart_transcript_variation__dm;
create index I_79 on VAR_MART_DB.SPECIES_ABBREV_snp__mart_transcript_variation__dm(variation_feature_id_2026_key);
create table VAR_MART_DB.TEMP69 as select a.clinical_significance as clinical_significance_2025,a.minor_allele_freq as minor_allele_freq_2025,a.source_id as source_id_2025,a.name as name_2025,a.ancestral_allele as ancestral_allele_2025,a.evidence as evidence_2025,a.minor_allele as minor_allele_2025,a.variation_id as variation_id_2025_key,a.minor_allele_count as minor_allele_count_2025 from VAR_DB.variation as a where a.somatic=1;
create index I_80 on VAR_MART_DB.TEMP69(source_id_2025);
create table VAR_MART_DB.TEMP70 as select a.*,b.description as description_2021,b.name as name_2021 from VAR_MART_DB.TEMP69 as a left join VAR_DB.source as b on a.source_id_2025=b.source_id;
drop table VAR_MART_DB.TEMP69;
alter table VAR_MART_DB.TEMP70 drop column source_id_2025;
create index I_81 on VAR_MART_DB.TEMP70(name_2025);
create index I_82 on VAR_MART_DB.TEMP70(name_2021);
create index I_83 on VAR_MART_DB.TEMP70(evidence_2025);
rename table VAR_MART_DB.TEMP70 to VAR_MART_DB.SPECIES_ABBREV_snp_som__variation__main;
create index I_84 on VAR_MART_DB.SPECIES_ABBREV_snp_som__variation__main(variation_id_2025_key);
create table VAR_MART_DB.TEMP71 as select a.source_id as source_id_2021,a.description as description_2021,a.name as name_2021 from VAR_DB.source as a;
create index I_85 on VAR_MART_DB.TEMP71(source_id_2021);
create table VAR_MART_DB.TEMP72 as select a.*,b.subsnp_id as subsnp_id_2030,b.name as name_2030,b.variation_id as variation_id_2025_key,b.variation_synonym_id as variation_synonym_id_2030 from VAR_MART_DB.TEMP71 as a inner join VAR_DB.variation_synonym as b on a.source_id_2021=b.source_id;
drop table VAR_MART_DB.TEMP71;
create index I_86 on VAR_MART_DB.TEMP72(variation_id_2025_key);
create table VAR_MART_DB.TEMP74 as select a.* from VAR_MART_DB.TEMP72 as a inner join VAR_MART_DB.SPECIES_ABBREV_snp_som__variation__main as b on a.variation_id_2025_key=b.variation_id_2025_key;
drop table VAR_MART_DB.TEMP72;
create index I_87 on VAR_MART_DB.TEMP74(variation_id_2025_key);
create table VAR_MART_DB.TEMP75 as select a.variation_id_2025_key,b.source_id_2021,b.description_2021,b.variation_synonym_id_2030,b.name_2030,b.name_2021,b.subsnp_id_2030 from VAR_MART_DB.SPECIES_ABBREV_snp_som__variation__main as a left join VAR_MART_DB.TEMP74 as b on a.variation_id_2025_key=b.variation_id_2025_key;
drop table VAR_MART_DB.TEMP74;
alter table VAR_MART_DB.TEMP75 drop column variation_synonym_id_2030;
alter table VAR_MART_DB.TEMP75 drop column subsnp_id_2030;
create index I_88 on VAR_MART_DB.TEMP75(name_2030);
create index I_89 on VAR_MART_DB.TEMP75(name_2021);
rename table VAR_MART_DB.TEMP75 to VAR_MART_DB.SPECIES_ABBREV_snp_som__variation_synonym__dm;
create index I_90 on VAR_MART_DB.SPECIES_ABBREV_snp_som__variation_synonym__dm(variation_id_2025_key);
create table VAR_MART_DB.TEMP76 as select a.variation_id_2025_key from VAR_MART_DB.SPECIES_ABBREV_snp_som__variation__main as a;
create index I_91 on VAR_MART_DB.TEMP76(variation_id_2025_key);
create table VAR_MART_DB.TEMP77 as select a.*,b.subsnp_id as subsnp_id_2023,b.allele_1 as allele_1_2023,b.allele_2 as allele_2_2023,b.individual_id as individual_id_2023 from VAR_MART_DB.TEMP76 as a left join VAR_DB.tmp_individual_genotype_single_bp as b on a.variation_id_2025_key=b.variation_id;
drop table VAR_MART_DB.TEMP76;
create index I_92 on VAR_MART_DB.TEMP77(individual_id_2023);
create table VAR_MART_DB.TEMP79 as select a.*,b.individual_type_id as individual_type_id_2019,b.name as name_2019 from VAR_MART_DB.TEMP77 as a inner join VAR_DB.individual as b on a.individual_id_2023=b.individual_id and (b.display in ("REFERENCE","DEFAULT","DISPLAYABLE","MARTDISPLAYABLE"));
drop table VAR_MART_DB.TEMP77;
create index I_93 on VAR_MART_DB.TEMP79(individual_type_id_2019);
create table VAR_MART_DB.TEMP81 as select a.* from VAR_MART_DB.TEMP79 as a left join VAR_DB.individual_type as b on a.individual_type_id_2019=b.individual_type_id;
drop table VAR_MART_DB.TEMP79;
create table VAR_MART_DB.TEMP82 as select individual_id_2023,individual_type_id_2019,name_2019,allele_2_2023,variation_id_2025_key,subsnp_id_2023,allele_1_2023,concat(allele_1_2023, '|', allele_2_2023) as allele from VAR_MART_DB.TEMP81;
drop table VAR_MART_DB.TEMP81;
create index I_94 on VAR_MART_DB.TEMP82(variation_id_2025_key);
create table VAR_MART_DB.TEMP83 as select a.variation_id_2025_key,b.individual_id_2023,b.subsnp_id_2023,b.individual_type_id_2019,b.allele,b.allele_2_2023,b.allele_1_2023,b.name_2019 from VAR_MART_DB.SPECIES_ABBREV_snp_som__variation__main as a left join VAR_MART_DB.TEMP82 as b on a.variation_id_2025_key=b.variation_id_2025_key;
drop table VAR_MART_DB.TEMP82;
create table VAR_MART_DB.TEMP84 as select distinct individual_id_2023,name_2019,allele,variation_id_2025_key from VAR_MART_DB.TEMP83;
drop table VAR_MART_DB.TEMP83;
create index I_95 on VAR_MART_DB.TEMP84(name_2019);
rename table VAR_MART_DB.TEMP84 to VAR_MART_DB.SPECIES_ABBREV_snp_som__poly__dm;
create index I_96 on VAR_MART_DB.SPECIES_ABBREV_snp_som__poly__dm(variation_id_2025_key);
create table VAR_MART_DB.TEMP85 as select a.variation_id_2025_key from VAR_MART_DB.SPECIES_ABBREV_snp_som__variation__main as a;
create index I_97 on VAR_MART_DB.TEMP85(variation_id_2025_key);
create table VAR_MART_DB.TEMP86 as select a.*,b.population_genotype_id as population_genotype_id_20107,b.allele_1 as allele_1_20107,b.population_id as population_id_20107,b.allele_2 as allele_2_20107,b.frequency as frequency_2016 from VAR_MART_DB.TEMP85 as a inner join VAR_DB.MTMP_population_genotype as b on a.variation_id_2025_key=b.variation_id;
drop table VAR_MART_DB.TEMP85;
create index I_98 on VAR_MART_DB.TEMP86(population_id_20107);
create table VAR_MART_DB.TEMP87 as select a.*,b.name as name_2019,b.size as size_2019 from VAR_MART_DB.TEMP86 as a inner join VAR_DB.population as b on a.population_id_20107=b.population_id;
drop table VAR_MART_DB.TEMP86;
create table VAR_MART_DB.TEMP88 as select name_2019,frequency_2016,size_2019,allele_2_20107,population_id_20107,variation_id_2025_key,allele_1_20107,population_genotype_id_20107,concat(allele_1_20107, '|', allele_2_20107) as allele from VAR_MART_DB.TEMP87;
drop table VAR_MART_DB.TEMP87;
create index I_99 on VAR_MART_DB.TEMP88(variation_id_2025_key);
create table VAR_MART_DB.TEMP89 as select a.variation_id_2025_key,b.name_2019,b.allele_1_20107,b.population_id_20107,b.allele,b.population_genotype_id_20107,b.size_2019,b.allele_2_20107,b.frequency_2016 from VAR_MART_DB.SPECIES_ABBREV_snp_som__variation__main as a left join VAR_MART_DB.TEMP88 as b on a.variation_id_2025_key=b.variation_id_2025_key;
drop table VAR_MART_DB.TEMP88;
alter table VAR_MART_DB.TEMP89 drop column allele_1_20107;
alter table VAR_MART_DB.TEMP89 drop column population_id_20107;
alter table VAR_MART_DB.TEMP89 drop column population_genotype_id_20107;
alter table VAR_MART_DB.TEMP89 drop column allele_2_20107;
rename table VAR_MART_DB.TEMP89 to VAR_MART_DB.SPECIES_ABBREV_snp_som__population_genotype__dm;
create index I_100 on VAR_MART_DB.SPECIES_ABBREV_snp_som__population_genotype__dm(variation_id_2025_key);
alter table VAR_MART_DB.SPECIES_ABBREV_snp_som__variation__main add column (population_genotype_bool integer default 0);
update VAR_MART_DB.SPECIES_ABBREV_snp_som__variation__main a set population_genotype_bool=(select case count(1) when 0 then null else 1 end from VAR_MART_DB.SPECIES_ABBREV_snp_som__population_genotype__dm b where a.variation_id_2025_key=b.variation_id_2025_key and not (b.name_2019 is null and b.size_2019 is null and b.frequency_2016 is null));
create index I_101 on VAR_MART_DB.SPECIES_ABBREV_snp_som__variation__main(population_genotype_bool);
create table VAR_MART_DB.TEMP90 as select a.variation_id_2025_key from VAR_MART_DB.SPECIES_ABBREV_snp_som__variation__main as a;
create index I_102 on VAR_MART_DB.TEMP90(variation_id_2025_key);
create table VAR_MART_DB.TEMP91 as select a.*,b.variation_set_id as variation_set_id_2078 from VAR_MART_DB.TEMP90 as a inner join VAR_DB.MTMP_variation_set_variation as b on a.variation_id_2025_key=b.variation_id;
drop table VAR_MART_DB.TEMP90;
create index I_103 on VAR_MART_DB.TEMP91(variation_set_id_2078);
create table VAR_MART_DB.TEMP92 as select a.*,b.description as description_2077,b.name as name_2077 from VAR_MART_DB.TEMP91 as a inner join VAR_DB.variation_set as b on a.variation_set_id_2078=b.variation_set_id;
drop table VAR_MART_DB.TEMP91;
create index I_104 on VAR_MART_DB.TEMP92(variation_id_2025_key);
create table VAR_MART_DB.TEMP93 as select a.variation_id_2025_key,b.variation_set_id_2078,b.description_2077,b.name_2077 from VAR_MART_DB.SPECIES_ABBREV_snp_som__variation__main as a left join VAR_MART_DB.TEMP92 as b on a.variation_id_2025_key=b.variation_id_2025_key;
drop table VAR_MART_DB.TEMP92;
rename table VAR_MART_DB.TEMP93 to VAR_MART_DB.SPECIES_ABBREV_snp_som__variation_set_variation__dm;
create index I_105 on VAR_MART_DB.SPECIES_ABBREV_snp_som__variation_set_variation__dm(variation_id_2025_key);
create table VAR_MART_DB.TEMP94 as select a.variation_id_2025_key from VAR_MART_DB.SPECIES_ABBREV_snp_som__variation__main as a;
create index I_106 on VAR_MART_DB.TEMP94(variation_id_2025_key);
create table VAR_MART_DB.TEMP95 as select a.*,b.subsnp_id as subsnp_id_2010,b.allele_1 as allele_1_2010,b.allele_2 as allele_2_2010,b.individual_id as individual_id_2010 from VAR_MART_DB.TEMP94 as a left join VAR_DB.individual_genotype_multiple_bp as b on a.variation_id_2025_key=b.variation_id;
drop table VAR_MART_DB.TEMP94;
create index I_107 on VAR_MART_DB.TEMP95(individual_id_2010);
create table VAR_MART_DB.TEMP97 as select a.*,b.individual_type_id as individual_type_id_2019,b.name as name_2019 from VAR_MART_DB.TEMP95 as a inner join VAR_DB.individual as b on a.individual_id_2010=b.individual_id and (b.display in ("REFERENCE","DEFAULT","DISPLAYABLE","MARTDISPLAYABLE"));
drop table VAR_MART_DB.TEMP95;
create index I_108 on VAR_MART_DB.TEMP97(individual_type_id_2019);
create table VAR_MART_DB.TEMP99 as select a.* from VAR_MART_DB.TEMP97 as a left join VAR_DB.individual_type as b on a.individual_type_id_2019=b.individual_type_id;
drop table VAR_MART_DB.TEMP97;
create table VAR_MART_DB.TEMP100 as select individual_type_id_2019,name_2019,individual_id_2010,allele_2_2010,variation_id_2025_key,subsnp_id_2010,allele_1_2010,concat(allele_1_2010, '|', allele_2_2010) as allele from VAR_MART_DB.TEMP99;
drop table VAR_MART_DB.TEMP99;
create index I_109 on VAR_MART_DB.TEMP100(variation_id_2025_key);
create table VAR_MART_DB.TEMP101 as select a.variation_id_2025_key,b.individual_id_2010,b.individual_type_id_2019,b.allele_2_2010,b.allele_1_2010,b.allele,b.subsnp_id_2010,b.name_2019 from VAR_MART_DB.SPECIES_ABBREV_snp_som__variation__main as a left join VAR_MART_DB.TEMP100 as b on a.variation_id_2025_key=b.variation_id_2025_key;
drop table VAR_MART_DB.TEMP100;
create table VAR_MART_DB.TEMP102 as select distinct name_2019,individual_id_2010,allele,variation_id_2025_key from VAR_MART_DB.TEMP101;
drop table VAR_MART_DB.TEMP101;
create index I_110 on VAR_MART_DB.TEMP102(name_2019);
rename table VAR_MART_DB.TEMP102 to VAR_MART_DB.SPECIES_ABBREV_snp_som__mpoly__dm;
create index I_111 on VAR_MART_DB.SPECIES_ABBREV_snp_som__mpoly__dm(variation_id_2025_key);
create table VAR_MART_DB.TEMP103 as select a.variation_id_2025_key from VAR_MART_DB.SPECIES_ABBREV_snp_som__variation__main as a;
create index I_112 on VAR_MART_DB.TEMP103(variation_id_2025_key);
create table VAR_MART_DB.TEMP104 as select a.*,b.risk_allele as associated_variant_risk_allele_2035,b.study_id as study_id_2035,b.is_significant as is_significant_20133,b.associated_gene as associated_gene_2035,b.p_value as p_value_2035,b.variation_names as variation_names_2035,b.phenotype_id as phenotype_id_2035 from VAR_MART_DB.TEMP103 as a inner join VAR_DB.MTMP_variation_annotation as b on a.variation_id_2025_key=b.variation_id;
drop table VAR_MART_DB.TEMP103;
create index I_113 on VAR_MART_DB.TEMP104(phenotype_id_2035);
create table VAR_MART_DB.TEMP105 as select a.*,b.stable_id as stable_id_2033,b.description as description_2033 from VAR_MART_DB.TEMP104 as a inner join VAR_DB.phenotype as b on a.phenotype_id_2035=b.phenotype_id;
drop table VAR_MART_DB.TEMP104;
create index I_114 on VAR_MART_DB.TEMP105(study_id_2035);
create table VAR_MART_DB.TEMP106 as select a.*,b.external_reference as external_reference_20100,b.source_id as source_id_20100,b.description as description_20100,b.study_type as study_type_20100 from VAR_MART_DB.TEMP105 as a left join VAR_DB.study as b on a.study_id_2035=b.study_id;
drop table VAR_MART_DB.TEMP105;
create index I_115 on VAR_MART_DB.TEMP106(source_id_20100);
create table VAR_MART_DB.TEMP107 as select a.*,b.name as name_2021 from VAR_MART_DB.TEMP106 as a left join VAR_DB.source as b on a.source_id_20100=b.source_id;
drop table VAR_MART_DB.TEMP106;
create index I_116 on VAR_MART_DB.TEMP107(variation_id_2025_key);
create table VAR_MART_DB.TEMP108 as select a.variation_id_2025_key,b.associated_variant_risk_allele_2035,b.is_significant_20133,b.source_id_20100,b.stable_id_2033,b.associated_gene_2035,b.external_reference_20100,b.description_20100,b.phenotype_id_2035,b.study_type_20100,b.description_2033,b.name_2021,b.study_id_2035,b.p_value_2035,b.variation_names_2035 from VAR_MART_DB.SPECIES_ABBREV_snp_som__variation__main as a left join VAR_MART_DB.TEMP107 as b on a.variation_id_2025_key=b.variation_id_2025_key;
drop table VAR_MART_DB.TEMP107;
alter table VAR_MART_DB.TEMP108 drop column phenotype_id_2035;
create index I_117 on VAR_MART_DB.TEMP108(study_type_20100);
create index I_118 on VAR_MART_DB.TEMP108(description_2033);
rename table VAR_MART_DB.TEMP108 to VAR_MART_DB.SPECIES_ABBREV_snp_som__variation_annotation__dm;
create index I_119 on VAR_MART_DB.SPECIES_ABBREV_snp_som__variation_annotation__dm(variation_id_2025_key);
alter table VAR_MART_DB.SPECIES_ABBREV_snp_som__variation__main add column (variation_annotation_bool integer default 0);
update VAR_MART_DB.SPECIES_ABBREV_snp_som__variation__main a set variation_annotation_bool=(select case count(1) when 0 then null else 1 end from VAR_MART_DB.SPECIES_ABBREV_snp_som__variation_annotation__dm b where a.variation_id_2025_key=b.variation_id_2025_key and not (b.associated_variant_risk_allele_2035 is null and b.is_significant_20133 is null and b.source_id_20100 is null and b.stable_id_2033 is null and b.associated_gene_2035 is null and b.external_reference_20100 is null and b.description_20100 is null and b.study_type_20100 is null and b.description_2033 is null and b.name_2021 is null and b.study_id_2035 is null and b.p_value_2035 is null and b.variation_names_2035 is null));
create index I_120 on VAR_MART_DB.SPECIES_ABBREV_snp_som__variation__main(variation_annotation_bool);
create table VAR_MART_DB.TEMP109 as select a.variation_id_2025_key from VAR_MART_DB.SPECIES_ABBREV_snp_som__variation__main as a;
create index I_121 on VAR_MART_DB.TEMP109(variation_id_2025_key);
create table VAR_MART_DB.TEMP110 as select a.*,b.publication_id as publication_id_20139 from VAR_MART_DB.TEMP109 as a inner join VAR_DB.variation_citation as b on a.variation_id_2025_key=b.variation_id;
drop table VAR_MART_DB.TEMP109;
create index I_122 on VAR_MART_DB.TEMP110(publication_id_20139);
create table VAR_MART_DB.TEMP111 as select a.*,b.pmcid as pmcid_20137,b.authors as authors_20137,b.title as title_20137,b.pmid as pmid_20137,b.year as year_20137,b.ucsc_id as ucsc_id_20137,b.doi as doi_20137 from VAR_MART_DB.TEMP110 as a inner join VAR_DB.publication as b on a.publication_id_20139=b.publication_id;
drop table VAR_MART_DB.TEMP110;
create index I_123 on VAR_MART_DB.TEMP111(variation_id_2025_key);
create table VAR_MART_DB.TEMP112 as select a.variation_id_2025_key,b.ucsc_id_20137,b.title_20137,b.pmcid_20137,b.doi_20137,b.publication_id_20139,b.authors_20137,b.year_20137,b.pmid_20137 from VAR_MART_DB.SPECIES_ABBREV_snp_som__variation__main as a left join VAR_MART_DB.TEMP111 as b on a.variation_id_2025_key=b.variation_id_2025_key;
drop table VAR_MART_DB.TEMP111;
rename table VAR_MART_DB.TEMP112 to VAR_MART_DB.SPECIES_ABBREV_snp_som__variation_citation__dm;
create index I_124 on VAR_MART_DB.SPECIES_ABBREV_snp_som__variation_citation__dm(variation_id_2025_key);
alter table VAR_MART_DB.SPECIES_ABBREV_snp_som__variation__main add column (variation_citation_bool integer default 0);
update VAR_MART_DB.SPECIES_ABBREV_snp_som__variation__main a set variation_citation_bool=(select case count(1) when 0 then null else 1 end from VAR_MART_DB.SPECIES_ABBREV_snp_som__variation_citation__dm b where a.variation_id_2025_key=b.variation_id_2025_key and not (b.ucsc_id_20137 is null and b.title_20137 is null and b.pmcid_20137 is null and b.doi_20137 is null and b.publication_id_20139 is null and b.authors_20137 is null and b.year_20137 is null and b.pmid_20137 is null));
create index I_125 on VAR_MART_DB.SPECIES_ABBREV_snp_som__variation__main(variation_citation_bool);
create table VAR_MART_DB.TEMP113 as select a.description_2021,a.name_2021,a.name_2025,a.minor_allele_freq_2025,a.variation_citation_bool,a.minor_allele_2025,a.minor_allele_count_2025,a.ancestral_allele_2025,a.clinical_significance_2025,a.variation_id_2025_key,a.variation_annotation_bool,a.evidence_2025,a.population_genotype_bool from VAR_MART_DB.SPECIES_ABBREV_snp_som__variation__main as a;
create index I_126 on VAR_MART_DB.TEMP113(variation_id_2025_key);
create table VAR_MART_DB.TEMP114 as select a.*,b.variation_feature_id as variation_feature_id_2026_key,b.seq_region_id as seq_region_id_2026,b.clinical_significance as clinical_significance_2026,b.seq_region_start as seq_region_start_2026,b.variation_name as variation_name_2026,b.source_id as source_id_2026,b.map_weight as map_weight_2026,b.variation_set_id as variation_set_id_2026,b.seq_region_strand as seq_region_strand_2026,b.seq_region_end as seq_region_end_2026,b.allele_string as allele_string_2026 from VAR_MART_DB.TEMP113 as a inner join VAR_DB.variation_feature as b on a.variation_id_2025_key=b.variation_id;
drop table VAR_MART_DB.TEMP113;
create index I_127 on VAR_MART_DB.TEMP114(source_id_2026);
create table VAR_MART_DB.TEMP115 as select a.* from VAR_MART_DB.TEMP114 as a inner join VAR_DB.source as b on a.source_id_2026=b.source_id;
drop table VAR_MART_DB.TEMP114;
create index I_128 on VAR_MART_DB.TEMP115(seq_region_id_2026);
create table VAR_MART_DB.TEMP116 as select a.*,b.name as name_1059,b.coord_system_id as coord_system_id_1059 from VAR_MART_DB.TEMP115 as a inner join CORE_DB.seq_region as b on a.seq_region_id_2026=b.seq_region_id;
drop table VAR_MART_DB.TEMP115;
create index I_129 on VAR_MART_DB.TEMP116(seq_region_id_2026);
create table VAR_MART_DB.TEMP118 as select a.*,b.coord_system_id as coord_system_id_2034 from VAR_MART_DB.TEMP116 as a inner join VAR_DB.seq_region as b on a.seq_region_id_2026=b.seq_region_id;
drop table VAR_MART_DB.TEMP116;
create index I_130 on VAR_MART_DB.TEMP118(variation_set_id_2026);
create table VAR_MART_DB.TEMP119 as select a.* from VAR_MART_DB.TEMP118 as a left join VAR_DB.variation_set as b on a.variation_set_id_2026=b.variation_set_id;
drop table VAR_MART_DB.TEMP118;
create index I_131 on VAR_MART_DB.TEMP119(variation_id_2025_key);
create table VAR_MART_DB.TEMP120 as select a.variation_id_2025_key,b.description_2021,b.clinical_significance_2026,b.coord_system_id_2034,b.seq_region_start_2026,b.clinical_significance_2025,b.variation_feature_id_2026_key,b.variation_set_id_2026,b.allele_string_2026,b.minor_allele_2025,b.name_1059,b.ancestral_allele_2025,b.evidence_2025,b.coord_system_id_1059,b.minor_allele_freq_2025,b.source_id_2026,b.name_2021,b.seq_region_id_2026,b.name_2025,b.seq_region_end_2026,b.seq_region_strand_2026,b.minor_allele_count_2025,b.variation_name_2026,b.map_weight_2026,b.variation_citation_bool,b.variation_annotation_bool,b.population_genotype_bool from VAR_MART_DB.SPECIES_ABBREV_snp_som__variation__main as a left join VAR_MART_DB.TEMP119 as b on a.variation_id_2025_key=b.variation_id_2025_key;
drop table VAR_MART_DB.TEMP119;
alter table VAR_MART_DB.TEMP120 drop column coord_system_id_2034;
alter table VAR_MART_DB.TEMP120 drop column coord_system_id_1059;
alter table VAR_MART_DB.TEMP120 drop column source_id_2026;
create index I_132 on VAR_MART_DB.TEMP120(seq_region_start_2026);
create index I_133 on VAR_MART_DB.TEMP120(name_1059);
create index I_134 on VAR_MART_DB.TEMP120(name_2025);
rename table VAR_MART_DB.TEMP120 to VAR_MART_DB.SPECIES_ABBREV_snp_som__variation_feature__main;
create index I_135 on VAR_MART_DB.SPECIES_ABBREV_snp_som__variation_feature__main(variation_id_2025_key);
create index I_136 on VAR_MART_DB.SPECIES_ABBREV_snp_som__variation_feature__main(variation_feature_id_2026_key);
alter table VAR_MART_DB.SPECIES_ABBREV_snp_som__variation__main add column (variation_feature_count integer default 0);
update VAR_MART_DB.SPECIES_ABBREV_snp_som__variation__main a set variation_feature_count=(select count(1) from VAR_MART_DB.SPECIES_ABBREV_snp_som__variation_feature__main b where a.variation_id_2025_key=b.variation_id_2025_key and not (b.description_2021 is null and b.clinical_significance_2026 is null and b.seq_region_start_2026 is null and b.clinical_significance_2025 is null and b.variation_feature_id_2026_key is null and b.variation_set_id_2026 is null and b.allele_string_2026 is null and b.minor_allele_2025 is null and b.name_1059 is null and b.ancestral_allele_2025 is null and b.evidence_2025 is null and b.minor_allele_freq_2025 is null and b.name_2021 is null and b.seq_region_id_2026 is null and b.name_2025 is null and b.seq_region_end_2026 is null and b.seq_region_strand_2026 is null and b.minor_allele_count_2025 is null and b.variation_name_2026 is null and b.map_weight_2026 is null));
create index I_137 on VAR_MART_DB.SPECIES_ABBREV_snp_som__variation__main(variation_feature_count);
alter table VAR_MART_DB.SPECIES_ABBREV_snp_som__variation_feature__main add column (variation_feature_count integer default 0);
update VAR_MART_DB.SPECIES_ABBREV_snp_som__variation_feature__main a set variation_feature_count=(select max(variation_feature_count) from VAR_MART_DB.SPECIES_ABBREV_snp_som__variation__main b where a.variation_id_2025_key=b.variation_id_2025_key);
create index I_138 on VAR_MART_DB.SPECIES_ABBREV_snp_som__variation_feature__main(variation_feature_count);
create table VAR_MART_DB.TEMP121 as select a.variation_feature_id_2026_key from VAR_MART_DB.SPECIES_ABBREV_snp_som__variation_feature__main as a;
create index I_139 on VAR_MART_DB.TEMP121(variation_feature_id_2026_key);
create table VAR_MART_DB.TEMP122 as select a.*,b.feature_stable_id as feature_stable_id_20126,b.consequence_types as consequence_types_20126,b.allele_string as allele_string_20126 from VAR_MART_DB.TEMP121 as a inner join VAR_DB.MTMP_regulatory_feature_variation as b on a.variation_feature_id_2026_key=b.variation_feature_id;
drop table VAR_MART_DB.TEMP121;
create index I_140 on VAR_MART_DB.TEMP122(variation_feature_id_2026_key);
create table VAR_MART_DB.TEMP123 as select a.variation_feature_id_2026_key,b.feature_stable_id_20126,b.allele_string_20126,b.consequence_types_20126 from VAR_MART_DB.SPECIES_ABBREV_snp_som__variation_feature__main as a left join VAR_MART_DB.TEMP122 as b on a.variation_feature_id_2026_key=b.variation_feature_id_2026_key;
drop table VAR_MART_DB.TEMP122;
create index I_141 on VAR_MART_DB.TEMP123(feature_stable_id_20126);
rename table VAR_MART_DB.TEMP123 to VAR_MART_DB.SPECIES_ABBREV_snp_som__regulatory_feature_variation__dm;
create index I_142 on VAR_MART_DB.SPECIES_ABBREV_snp_som__regulatory_feature_variation__dm(variation_feature_id_2026_key);
create table VAR_MART_DB.TEMP124 as select a.variation_feature_id_2026_key from VAR_MART_DB.SPECIES_ABBREV_snp_som__variation_feature__main as a;
create index I_143 on VAR_MART_DB.TEMP124(variation_feature_id_2026_key);
create table VAR_MART_DB.TEMP125 as select a.*,b.feature_stable_id as feature_stable_id_20125,b.motif_name as motif_name_20125,b.in_informative_position as in_informative_position_20125,b.motif_score_delta as motif_score_delta_20125,b.consequence_types as consequence_types_20125,b.motif_start as motif_start_20125,b.allele_string as allele_string_20125 from VAR_MART_DB.TEMP124 as a inner join VAR_DB.MTMP_motif_feature_variation as b on a.variation_feature_id_2026_key=b.variation_feature_id;
drop table VAR_MART_DB.TEMP124;
create index I_144 on VAR_MART_DB.TEMP125(variation_feature_id_2026_key);
create table VAR_MART_DB.TEMP126 as select a.variation_feature_id_2026_key,b.allele_string_20125,b.motif_score_delta_20125,b.motif_name_20125,b.motif_start_20125,b.feature_stable_id_20125,b.consequence_types_20125,b.in_informative_position_20125 from VAR_MART_DB.SPECIES_ABBREV_snp_som__variation_feature__main as a left join VAR_MART_DB.TEMP125 as b on a.variation_feature_id_2026_key=b.variation_feature_id_2026_key;
drop table VAR_MART_DB.TEMP125;
rename table VAR_MART_DB.TEMP126 to VAR_MART_DB.SPECIES_ABBREV_snp_som__motif_feature_variation__dm;
create index I_145 on VAR_MART_DB.SPECIES_ABBREV_snp_som__motif_feature_variation__dm(variation_feature_id_2026_key);
create table VAR_MART_DB.TEMP127 as select a.seq_region_id as seq_region_id_1020,a.stable_id as stable_id_1023,a.analysis_id as analysis_id_1020,a.gene_id as gene_id_1020 from CORE_DB.gene as a;
create index I_146 on VAR_MART_DB.TEMP127(gene_id_1020);
create table VAR_MART_DB.TEMP130 as select a.*,b.transcript_id as transcript_id_1064,b.seq_region_id as seq_region_id_1064,b.stable_id as stable_id_1066,b.analysis_id as analysis_id_1064,b.biotype as biotype_1064,b.seq_region_strand as seq_region_strand_1064 from VAR_MART_DB.TEMP127 as a inner join CORE_DB.transcript as b on a.gene_id_1020=b.gene_id;
drop table VAR_MART_DB.TEMP127;
create index I_147 on VAR_MART_DB.TEMP130(stable_id_1066);
create table VAR_MART_DB.TEMP133 as select a.*,b.polyphen_prediction as polyphen_prediction_2090,b.cds_end as cds_end_2090,b.pep_allele_string as pep_allele_string_2090,b.cdna_end as cdna_end_2090,b.cds_start as cds_start_2090,b.sift_prediction as sift_prediction_2090,b.cdna_start as cdna_start_2090,b.allele_string as allele_string_2090,b.sift_score as sift_score_2090,b.variation_feature_id as variation_feature_id_2026_key,b.distance_to_transcript as distance_to_transcript_2090,b.consequence_types as consequence_types_2090,b.polyphen_score as polyphen_score_2090,b.translation_end as translation_end_2090,b.translation_start as translation_start_2090 from VAR_MART_DB.TEMP130 as a inner join VAR_DB.MTMP_transcript_variation as b on a.stable_id_1066=b.feature_stable_id;
drop table VAR_MART_DB.TEMP130;
create index I_148 on VAR_MART_DB.TEMP133(variation_feature_id_2026_key);
create table VAR_MART_DB.TEMP134 as select a.* from VAR_MART_DB.TEMP133 as a inner join VAR_MART_DB.SPECIES_ABBREV_snp_som__variation_feature__main as b on a.variation_feature_id_2026_key=b.variation_feature_id_2026_key;
drop table VAR_MART_DB.TEMP133;
create index I_149 on VAR_MART_DB.TEMP134(variation_feature_id_2026_key);
create table VAR_MART_DB.TEMP135 as select a.variation_feature_id_2026_key,b.allele_string_2090,b.stable_id_1066,b.sift_prediction_2090,b.distance_to_transcript_2090,b.cds_start_2090,b.stable_id_1023,b.cdna_end_2090,b.transcript_id_1064,b.gene_id_1020,b.polyphen_prediction_2090,b.translation_end_2090,b.sift_score_2090,b.cdna_start_2090,b.translation_start_2090,b.cds_end_2090,b.seq_region_id_1020,b.consequence_types_2090,b.seq_region_strand_1064,b.seq_region_id_1064,b.analysis_id_1064,b.polyphen_score_2090,b.pep_allele_string_2090,b.analysis_id_1020,b.biotype_1064 from VAR_MART_DB.SPECIES_ABBREV_snp_som__variation_feature__main as a left join VAR_MART_DB.TEMP134 as b on a.variation_feature_id_2026_key=b.variation_feature_id_2026_key;
drop table VAR_MART_DB.TEMP134;
alter table VAR_MART_DB.TEMP135 drop column transcript_id_1064;
alter table VAR_MART_DB.TEMP135 drop column seq_region_id_1020;
alter table VAR_MART_DB.TEMP135 drop column seq_region_id_1064;
alter table VAR_MART_DB.TEMP135 drop column analysis_id_1064;
alter table VAR_MART_DB.TEMP135 drop column analysis_id_1020;
create index I_150 on VAR_MART_DB.TEMP135(stable_id_1066);
create index I_151 on VAR_MART_DB.TEMP135(sift_prediction_2090);
create index I_152 on VAR_MART_DB.TEMP135(stable_id_1023);
create index I_153 on VAR_MART_DB.TEMP135(polyphen_prediction_2090);
create index I_154 on VAR_MART_DB.TEMP135(cdna_start_2090);
create index I_155 on VAR_MART_DB.TEMP135(translation_start_2090);
create index I_156 on VAR_MART_DB.TEMP135(consequence_types_2090);
rename table VAR_MART_DB.TEMP135 to VAR_MART_DB.SPECIES_ABBREV_snp_som__mart_transcript_variation__dm;
create index I_157 on VAR_MART_DB.SPECIES_ABBREV_snp_som__mart_transcript_variation__dm(variation_feature_id_2026_key);